#!/usr/bin/env python3
"""E7: cell-level leakage comparison of the sky130_fd_sc_hd flip-flop with the ASAP7 predictive 7 nm FinFET flip-flops.
ASAP7 liberty files (open, 7z-compressed) from https://github.com/The-OpenROAD-Project/asap7sc7p5t_28 (LIB/NLDM), e.g.
  git clone --depth 1 --filter=blob:none --sparse <url> asap7 && cd asap7 && git sparse-checkout set LIB/NLDM
  7z x LIB/NLDM/asap7sc7p5t_SEQ_{RVT,LVT,SLVT}_TT_nldm_220123.lib.7z
Usage: asap7_leakage.py <dir with the extracted .lib files>   -> results/explore/asap7_leakage.json, paper/numbers_asap7.tex"""
import re, sys, glob, json, statistics
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
def cell_leak(lib_text, name):
    cells = list(re.finditer(r'\n\s*cell\s*\(\s*"?([A-Za-z0-9_]+)"?\s*\)\s*\{', lib_text))
    for i, m in enumerate(cells):
        if m.group(1) != name: continue
        body = lib_text[m.end(): cells[i + 1].start() if i + 1 < len(cells) else len(lib_text)]
        vals = [float(x) for x in re.findall(r'leakage_power\s*\(\s*\)\s*\{[^}]*?value\s*:\s*"?([\d.eE+-]+)', body, re.S)]
        area = float(re.search(r'\barea\s*:\s*([\d.]+)', body).group(1))
        cl = re.search(r'cell_leakage_power\s*:\s*"?([\d.eE+-]+)', body)
        return dict(area_um2=area, states=len(vals), leak_mean=statistics.mean(vals) if vals else (float(cl.group(1)) if cl else None),
                    leak_max=max(vals) if vals else None, leak_min=min(vals) if vals else None)
    return None
out = {"note": "leakage in pW, mean over the state-dependent liberty values (cell_leakage_power for sky130); TT corner, 25 C"}
sky = open('/media/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib').read()
for c in ['dfxtp_1', 'dlxtp_1']:
    d = cell_leak(sky, f'sky130_fd_sc_hd__{c}'); d = {k: (v * 1e3 if k.startswith('leak') and v is not None else v) for k, v in d.items()}  # nW -> pW
    d.update(library='sky130_fd_sc_hd', voltage=1.8); out[f'sky130_{c}'] = d
libdir = sys.argv[1]
for flavour, suf in (('RVT', 'R'), ('LVT', 'L'), ('SLVT', 'SL')):
    f = glob.glob(f'{libdir}/asap7sc7p5t_SEQ_{flavour}_TT_*.lib')
    if not f: continue
    t = open(f[0], errors='replace').read()
    for c in ('DFFHQNx1', 'DHLx1'):
        d = cell_leak(t, f'{c}_ASAP7_75t_{suf}'); d.update(library=f'ASAP7 7.5T {flavour}', voltage=0.7); out[f'asap7_{flavour}_{c}'] = d
Path(ROOT / 'results/explore/asap7_leakage.json').write_text(json.dumps(out, indent=1))
ref = out['sky130_dfxtp_1']['leak_mean']
def si_power(pw):
    """pW value -> siunitx macro with an SI prefix (115 pW, 1.11 nW, 11.3 nW)."""
    return f"\\SI{{{pw:.3g}}}{{\\pico\\watt}}" if pw < 1000 else f"\\SI{{{pw/1000:.3g}}}{{\\nano\\watt}}"
L = ["% auto-generated by sw/asap7_leakage.py", f"\\newcommand{{\\leakSkyDff}}{{{si_power(ref)}}}"]
for flavour in ('RVT', 'LVT', 'SLVT'):
    k = f'asap7_{flavour}_DFFHQNx1'
    if k in out:
        v = out[k]['leak_mean']; L.append(f"\\newcommand{{\\leakAsapDff{flavour}}}{{{si_power(v)}}}"); L.append(f"\\newcommand{{\\leakRatioAsap{flavour}}}{{{v/ref:,.0f}}}")
        print(f"ASAP7 {flavour:4s} DFFHQNx1: {v:8.1f} pW  = {v/ref:6.0f} x sky130 dfxtp_1 ({ref:.1f} pW)")
Path(ROOT / 'paper/numbers_asap7.tex').write_text("\n".join(L) + "\n")
