#!/usr/bin/env python3
"""E12 (round 5): moving-block bootstrap confidence intervals of the test R2 of the released seed-0 integer models.
Per session, the per-bin predictions of the integer reference model over the test block are resampled in contiguous blocks of
BLOCK bins (1 s = 250 bins by default; the NeuroBench reach segments are not stored per bin in the prepared data, so fixed-length
blocks stand in for them), 1,000 times; the NeuroBench R2 is recomputed on every resample. The three-session mean interval uses the
same resample index for the three sessions (independent resampling per session). Writes results/explore/bootstrap.json and
paper/numbers_bootstrap.tex (\rTwoBoot{Lo,Hi}{A,B,C,Mean}, \rTwoBootBlock, \rTwoBootN)."""
import json, sys
from pathlib import Path
import numpy as np
sys.path.insert(0, str(Path(__file__).resolve().parent))
from snn_int import IntSNN, r2_neurobench
ROOT = Path(__file__).resolve().parent.parent
SESS = ["indy_20160622_01", "indy_20160630_01", "indy_20170131_02"]; SH = ["A", "B", "C"]
TAG = sys.argv[1] if len(sys.argv) > 1 else "H64_th256_k44_drop"; BLOCK = 250; NB = 1000
rng = np.random.default_rng(0)
out = {"tag": TAG, "block_bins": BLOCK, "resamples": NB, "sessions": {}}
per_sess_boot = []
for s in SESS:
    m = np.load(ROOT / "results/models" / f"{s}_{TAG}" / "model_int.npz"); d = np.load(ROOT / "data/prepared" / f"{s}.npz")
    X = d["spikes"] > 0; V = d["vel"]; ite = d["ind_test"]; lo, hi = int(ite[0]), int(ite[-1]) + 1
    ref = IntSNN(m["W1"].astype(np.int64), m["W2"].astype(np.int64), int(m["theta"]), int(m["k1"]), int(m["k2"]))
    Y, _ = ref.run(X[lo:hi]); pred = (m["G"] * Y / 4096.0 + m["B"]) * m["vel_std"] + m["vel_mean"]; true = V[lo:hi]
    n = hi - lo; nblk = int(np.ceil(n / BLOCK)); r2_point = r2_neurobench(pred, true)
    boots = np.empty(NB)
    for k in range(NB):
        starts = rng.integers(0, n - BLOCK, size=nblk)
        idx = (starts[:, None] + np.arange(BLOCK)[None, :]).ravel()[:n]
        boots[k] = r2_neurobench(pred[idx], true[idx])
    lo95, hi95 = np.percentile(boots, [2.5, 97.5])
    out["sessions"][s] = {"r2": float(r2_point), "ci95": [float(lo95), float(hi95)], "boot_mean": float(boots.mean()), "boot_sd": float(boots.std(ddof=1)), "test_bins": int(n)}
    per_sess_boot.append(boots); print(f"{s}: R2 {r2_point:.4f}  95% CI [{lo95:.4f}, {hi95:.4f}]  (bootstrap sd {boots.std(ddof=1):.4f})")
mean_boot = np.mean(per_sess_boot, axis=0); lo95, hi95 = np.percentile(mean_boot, [2.5, 97.5])
r2_mean = float(np.mean([out["sessions"][s]["r2"] for s in SESS]))
out["mean"] = {"r2": r2_mean, "ci95": [float(lo95), float(hi95)], "boot_sd": float(mean_boot.std(ddof=1))}
print(f"three-session mean: R2 {r2_mean:.4f}  95% CI [{lo95:.4f}, {hi95:.4f}]")
(ROOT / "results/explore").mkdir(exist_ok=True); json.dump(out, open(ROOT / "results/explore/bootstrap.json", "w"), indent=1)
M = ["% auto-generated by sw/bootstrap_r2.py"]
for s, sh in zip(SESS, SH):
    M += [f"\\newcommand{{\\rTwoBootLo{sh}}}{{{out['sessions'][s]['ci95'][0]:.3f}}}", f"\\newcommand{{\\rTwoBootHi{sh}}}{{{out['sessions'][s]['ci95'][1]:.3f}}}"]
M += [f"\\newcommand{{\\rTwoBootLoMean}}{{{lo95:.3f}}}", f"\\newcommand{{\\rTwoBootHiMean}}{{{hi95:.3f}}}", f"\\newcommand{{\\rTwoBootBlock}}{{{BLOCK}}}", f"\\newcommand{{\\rTwoBootN}}{{{NB:,}}}"]
(ROOT / "paper/numbers_bootstrap.tex").write_text("\n".join(M) + "\n"); print("wrote paper/numbers_bootstrap.tex")
