#!/usr/bin/env python3
"""Round 5 closing summary: assembles the final tables of every experiment from the JSON/CSV results into results/ROUND5_CLOSING.md
(called by sw/refresh_round5.sh, so it always reflects the latest collector output). Narrative and failures live in
results/run_log_round5.md; this file is the numbers-only companion referenced from there."""
import json, csv
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
D = json.load(open(ROOT / "results/designs.json"))
def f(v, nd=3):
    if v is None or v == "": return "--"
    if isinstance(v, str): return v
    if isinstance(v, int) or (isinstance(v, float) and v >= 1000): return f"{v:,.0f}"
    return f"{v:.{nd}g}"
L = ["# Round 5: closing tables (generated by sw/closing_round5.py)", "",
     "Common settings: 5 MHz (200 ns) clock for every core and the SoC; utilization policy 60 -> 20 % (placement density = utilization + 10 %),",
     "first DRC-clean, timing-clean run at all signoff corners accepted; per-pin OpenSTA power at TT 25 C 1.8 V on gate-level activity of the",
     "real test stream (zero-delay 500-bin window, annotated 200-bin window, streamed toggle counts for whole test blocks and 5,000-bin annotated",
     "windows); vdd-only SRAM22 liberty; leakage from the idle run; P_avg = E_bin x 250 /s + leakage (clock stopped between bins).", ""]
# ---- E1
L += ["## E1. Every core at the common clock (sky130)", "",
      "| core | util % | cells | area mm2 | setup / hold slack ns | cycles/bin | E zero-delay nJ (500 bins) | E annotated nJ | E block B nJ (bins) | E ann. 5,000 bins | latency us | leak total / logic uW | P_avg uW (zero / ann.) | bit-exact |",
      "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
for n, d in D.items():
    p = d.get("pnr", {}); e = d.get("event", {}); s = d.get("event_sdf", {}); fb = d.get("full", {}).get("indy_20160630_01", {})
    ann = f(s.get("energy_per_bin_nJ")) + ("†" if s.get("derived_from_glitch_window") else "")
    blk = fb.get("func", {}); bsd = fb.get("sdf", {})
    L.append(f"| {n} | {p.get('util_target_pct','--')} | {f(p.get('stdcells'))} | {f(p.get('instance_area_um2',0)/1e6 if p.get('instance_area_um2') else None)} | "
             f"{f(p.get('setup_ws_ns'),4)} / {f(p.get('hold_ws_ns'),3)} | {f(e.get('cycles_per_bin'),4)} | {f(e.get('energy_per_bin_nJ'))} | {ann} | "
             f"{f(blk.get('energy_per_bin_nJ'))}{' (' + f'{blk['tb']['bins']:,}' + ')' if blk else ''} | {f(bsd.get('energy_per_bin_nJ'))} | {f(e.get('latency_us'),2)} | "
             f"{f(d.get('idle',{}).get('leakage_uW'))} / {f((d.get('leak_split') or {}).get('leak_logic_uW'))} | {f(d.get('avg_power_uW_250Hz_clkstopped'))} / {f(d.get('avg_power_uW_250Hz_clkstopped_sdf'))} | "
             f"{'yes' if e.get('pass') else '--'} |")
L += ["", "† annotated value derived from the 50-bin annotated / zero-delay ratio of the same netlist (E9). Change against 50 MHz: `results/DESIGNS_50_vs_5.md`;",
      "per-corner slacks: `results/DESIGNS_corners5.md`; every attempt of the policy: `results/POLICY5.md`.", ""]
# ---- E2
L += ["## E2. Training grid hardened as 12-bit gated cores", "",
      "| H | synapses | mean R2 (5 seeds) | sd | min-max | E zero-delay nJ | E annotated nJ | P_avg uW | area mm2 | util % | on the front |", "|---|---|---|---|---|---|---|---|---|---|---|"]
for r in csv.DictReader(open(ROOT / "results/pareto.csv")):
    L.append(f"| {r['H']} | {float(r['density'])*100:g} % | {r['r2_int_mean']} | {r['r2_int_sd']} | {r['r2_int_min']}-{r['r2_int_max']} | {r['energy_per_bin_nJ'] or '--'} | {r['energy_per_bin_sdf_nJ'] or '--'} | {r['p_avg_250Hz_uW'] or '--'} | {r['area_mm2'] or '--'} | {r['util_pct'] or '--'} | {'yes' if r['pareto']=='True' else ''} |")
L += ["", "Figure F1 (`figures/pareto.pdf`) draws these with the reference cores; `results/pareto.csv`, `paper/numbers_pareto.tex`.", ""]
# ---- E3
L += ["## E3. Per-session netlists", "", "See `results/per_session.csv` / `paper/numbers_persession.tex` and the table in the run log (all nine netlists, whole blocks, bit-exact).", ""]
# ---- E4
L += ["## E4. Whole test blocks against the 500-bin window", "",
      "| core | session | bins | events/bin | E window nJ | E block nJ | block/window | per-bin mean +- sd (min-max) nJ | E ann. 5,000 bins | ann./block |", "|---|---|---|---|---|---|---|---|---|---|"]
for n, d in D.items():
    for s_, fb in d.get("full", {}).items():
        fu = fb.get("func"); 
        if not fu: continue
        pb = fb.get("func_perbin") or {}; sd = fb.get("sdf") or {}
        ew = d.get("event", {}).get("energy_per_bin_nJ"); eb = fu["energy_per_bin_nJ"]
        L.append(f"| {n} | {s_[5:]} | {fu['tb']['bins']:,} | {fu['tb']['events']/fu['tb']['bins']:.2f} | {f(ew)} | {f(eb)} | {f(eb/ew,3) if ew and s_=='indy_20160630_01' else '--'} | "
                 f"{f(pb.get('e_bin_mean_nJ'))} +- {f(pb.get('e_bin_sd_nJ'),2)} ({f(pb.get('e_bin_min_nJ'),2)}-{f(pb.get('e_bin_max_nJ'),2)}) | {f(sd.get('energy_per_bin_nJ'))}{' (' + f'{sd['tb']['bins']:,}' + ' bins)' if sd else ''} | {f(sd['energy_per_bin_nJ']/eb,3) if sd else '--'} |")
L += ["", "Transfer model of the programmable cores (E_bin = a + b x n_ev over the sessions): `results/explore/transfer5.json`, `paper/numbers_transfer5.tex`.", ""]
# ---- E5
P = json.load(open(ROOT / "results/pdks5.json"))
L += ["## E5. Cross-node study", "", "Full table: `results/PDKS5.md`, `paper/pdks_table.tex`, `paper/numbers_pdks.tex`, `results/pdks_pavg_vs_rate.csv` (figure F2). Glitch factors (annotated / zero-delay, same netlist):", "",
      "| kit | " + " | ".join(c for c in ("sp", "m12", "min32", "min16", "lmin2")) + " |", "|---|---|---|---|---|---|"]
kits = []
for k in P:
    kk = k.split("/")[0]
    if kk not in kits: kits.append(kk)
for kk in kits:
    row = []
    for c in ("sp", "m12", "min32", "min16", "lmin2"):
        d = P.get(f"{kk}/{c}"); g = d.get("glitch_factor") if d else None
        row.append(f(g, 3) if g else ("zero-delay only" if d and d.get("event") else "--"))
    L.append(f"| {kk} | " + " | ".join(row) + " |")
L.append("")
# ---- E9
L += ["## E9. Annotated glitch factor of the standard-cell weight memories (50-bin window)", "", "| core | E zero-delay nJ (50 bins) | E annotated nJ (50 bins) | factor | applied to the 500-bin window: E ann. nJ | P_avg ann. uW |", "|---|---|---|---|---|---|"]
for n in ("bmi_snn_lmin2", "bmi_snn_lmem2"):
    try:
        vals = {}
        for tag in ("func_w50", "sdf_w50"):
            s = json.load(open(ROOT / f"power/out_{n}_5m_{tag}_indy_20160630_01/activity_summary.json"))
            tot = [l for l in open(ROOT / f"power/out_{n}_5m_{tag}_indy_20160630_01/power_vcd.rpt").read().splitlines() if l.startswith("Total")][0].split()
            vals[tag] = float(tot[4]) * s["cycles"] * 200e-9 / 50 * 1e9
        d = D.get(n, {})
        L.append(f"| {n} | {vals['func_w50']:.2f} | {vals['sdf_w50']:.2f} | {vals['sdf_w50']/vals['func_w50']:.3f} | {f(d.get('event_sdf',{}).get('energy_per_bin_nJ'))} | {f(d.get('avg_power_uW_250Hz_clkstopped_sdf'))} |")
    except Exception as ex: L.append(f"| {n} | -- | -- | -- | -- | -- |")
L.append("")
# ---- E14
C5 = json.load(open(ROOT / "results/corners5.json"))
L += ["## E14. Low-voltage cores: hardened with 1.28 V signoff against the 1.8 V netlist re-evaluated at 1.28 V", "",
      "| core | 1.8 V netlist: util %, cells, E ann. nJ, P_avg uW | re-evaluated at ss_n40C_1v28: setup / hold slack ns, f_max MHz, E ann. nJ, leak uW | 1.28 V-signoff netlist: util %, cells, E ann. nJ, leak uW, P_avg uW | re-hardened / re-evaluated |", "|---|---|---|---|---|"]
for n, r in C5.items():
    tt = r.get("tt", {}); lv = r.get("lv", {}); el = tt.get("e_lowv") or {}; es = lv.get("e_sdf_1v28") or {}; d = D.get(n, {})
    L.append(f"| {n} | {d.get('pnr',{}).get('util_target_pct','--')}, {f(tt.get('cells'))}, {f(d.get('event_sdf',{}).get('energy_per_bin_nJ'))}, {f(d.get('avg_power_uW_250Hz_clkstopped_sdf'))} | "
             f"{f(el.get('setup_ws_ns'),4)} / {f(el.get('hold_ws_ns'),3)}, {f(el.get('fmax_MHz'),3)}, {f(el.get('energy_per_bin_nJ'))}, {f(el.get('leakage_uW'))} | "
             f"{lv.get('util_pct','--')}, {f(lv.get('cells'))}, {f(es.get('energy_per_bin_nJ'))}, {f(lv.get('leak_1v28_uW'))}, {f(lv.get('pavg_250Hz_uW'))} | "
             f"{f(es['energy_per_bin_nJ']/el['energy_per_bin_nJ'],3) if es and el else '--'} |")
L += ["", "`paper/corners_table5.tex`, `paper/numbers_corners5.tex`, `results/corners5.json`.", ""]
# ---- other experiments: pointers
L += ["## E7, E10, E11, E12, E8", "",
      "- E7 software baseline, per-pin method over the decoding window (50 and 5 MHz, -O2 and hand-tuned): `paper/numbers_software5.tex`, run-log section E7.",
      "- E10 digital front end: `paper/numbers_frontend.tex`, `results/frontend.json` (root-clock correction: `power/root_clock_correction.json`).",
      "- E11 SRAM22 per-access figures and the published comparison: run-log sections E11.",
      "- E12 bootstrap confidence intervals: `paper/numbers_bootstrap.tex`, `results/bootstrap.json`.",
      "- E8 (one state width for every core) was not run; the run log records why.", "",
      "## Deliverables", "",
      "`results/run_log_round5.md` (narrative, chronological), this file, `results/{designs,pdks5,corners5,policy5,bootstrap,frontend}.json`, `results/{pareto,per_session,pdks_pavg_vs_rate}.csv`,",
      "`results/{DESIGNS,DESIGNS_50_vs_5,DESIGNS_corners5,PDKS5,POLICY5}.md`, `paper/numbers*.tex` and `paper/*_table*.tex` (regenerated by `sw/refresh_round5.sh`),",
      "figures F1-F3 and F5 as PDF/PNG with CSV in `figures/` (F4 in the manuscript's figure folder), raw reports in `results/raw/round5/`,",
      "previous versions in the manuscript's `_superseded/2026-09-19_before_round5/`."]
(ROOT / "results/ROUND5_CLOSING.md").write_text("\n".join(L) + "\n"); print("wrote results/ROUND5_CLOSING.md", len(L), "lines")
