#!/usr/bin/env python3
"""Round 6 (E1): software baseline on the same window as the cores. Sources: power/out_soc_<fw>_5m_100/ (100-bin decoding window at
5 MHz, -O2 and hand-tuned firmware, per-pin method: window.json, pwr/power_vcd.rpt, idle/pwr/power_vcd.rpt), the round-5 16-bin
windows power/out_soc_<fw>_5m/, the event counts of the windows (firmware headers), and the cores' matching windows
(power/out_bmi_snn_<core>_5m_{sdf,func}_w{100,500}_indy_20160630_01, the 500-bin E1 window and the 5,000-bin block window).
Writes results/explore/software6.json and paper/numbers_software6.tex (macros \\cpuW<Fw><Win>..., ratios \\ratioW<Win><Core>...)."""
import json, sys, re
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from collect_results import parse_group_table, RATE
from collect_designs5 import run_energy
ROOT = Path(__file__).resolve().parent.parent; T = 200.0
D = json.load(open(ROOT / "results/designs.json"))
out = {}; M = ["% auto-generated by sw/collect_software6.py (round 6, E1: software and cores on the same decoding window)"]
from fmt3 import sig as _sig
def f(x, nd=3): return _sig(x, nd)   # round 7: three significant digits with trailing zeros
def mac(n, v, nd=3): M.append(f"\\newcommand{{\\{n}}}{{{f(v, nd)}}}")
# ---- event counts of the windows (first bins of the test block of indy_20160630_01)
stats = json.load(open(ROOT / "sim/vecfull_indy_20160630_01/stats.json"))
def events_first(n):
    toks = [int(x, 16) for x in open(ROOT / "sim/vecfull_indy_20160630_01/stream.hex").read().split()]
    b = ev = 0
    for t in toks:
        if t == 0xFF:
            b += 1
            if b == n: break
        elif t != 0xFE: ev += 1
    return ev
EV = {16: events_first(16), 100: events_first(100), 500: events_first(500), 5000: events_first(5000)}
WN = {16: "Sixteen", 100: "Hund", 500: "FiveH", 5000: "FiveK"}                       # LaTeX macro names cannot carry digits
for n, e in EV.items(): mac(f"evWin{WN[n]}", e, 4); mac(f"evPerBinWin{WN[n]}", e / n)
out["window_events"] = EV
# ---- software windows
for fw, sh in (("o2", "Otwo"), ("tuned", "Tuned")):
    for nb, tag, wsh in ((16, f"out_soc_{fw}_5m", "Sixteen"), (100, f"out_soc_{fw}_5m_100", "Hund")):
        base = ROOT / "power" / tag
        if not (base / "pwr/power_vcd.rpt").exists(): continue
        w = json.load(open(base / "window.json")); g = parse_group_table(base / "pwr/power_vcd.rpt")
        cyc = w["cycles_in_window"]; Tw = cyc * T * 1e-9; P = g["Total"]["total"]
        r = dict(firmware=fw, n_bins=nb, cycles_per_bin=cyc / nb, events=EV[nb], events_per_bin=EV[nb] / nb, power_window_mW=P * 1e3,
                 energy_per_bin_nJ=P * Tw / nb * 1e9, leakage_uW=g["Total"]["leakage"] * 1e6)
        if (base / "idle/pwr/power_vcd.rpt").exists(): r["idle_power_uW"] = parse_group_table(base / "idle/pwr/power_vcd.rpt")["Total"]["total"] * 1e6
        r["avg_power_uW_250Hz_clkstopped"] = r["energy_per_bin_nJ"] * RATE * 1e-3 + r["leakage_uW"]
        out[f"{fw}_5m_{nb}"] = r; s = f"{sh}{wsh}"
        mac(f"eCpuW{s}", r["energy_per_bin_nJ"], 4); mac(f"cycCpuW{s}", r["cycles_per_bin"], 4); mac(f"pWinCpuW{s}", r["power_window_mW"]); mac(f"pAvgStopCpuW{s}", r["avg_power_uW_250Hz_clkstopped"])
# ---- the cores on the same windows
CORES = (("bmi_snn_sp", "Sp"), ("bmi_snn_m12", "MinT"), ("bmi_snn_top", "Seq"))
cores = {}
for core, csh in CORES:
    d = D.get(core, {}); c = {}
    for nb, wsh in ((100, "Hund"), (500, "FiveH")):
        es = run_energy(f"{core}_5m_sdf_w{nb}_indy_20160630_01", T, "u_wmem" if core == "bmi_snn_top" else None)
        ef = run_energy(f"{core}_5m_func_w{nb}_indy_20160630_01", T, "u_wmem" if core == "bmi_snn_top" else None) or (d.get("event") if nb == 500 else None)   # 500 bins zero-delay: own run where it exists, else the round-5 window
        c[nb] = dict(sdf=es["energy_per_bin_nJ"] if es else None, func=ef["energy_per_bin_nJ"] if ef else None)
        mac(f"eW{wsh}Sdf{csh}", c[nb]["sdf"]); mac(f"eW{wsh}Func{csh}", c[nb]["func"])
    fb = d.get("full", {}).get("indy_20160630_01", {}); c[5000] = dict(sdf=(fb.get("sdf") or {}).get("energy_per_bin_nJ"), func=(fb.get("func") or {}).get("energy_per_bin_nJ"))
    cores[core] = c
out["cores"] = cores
# ---- ratios software / core on the same window (annotated where the core has it)
for fw, sh in (("o2", "Otwo"), ("tuned", "Tuned")):
    for nb, wsh in ((16, "Sixteen"), (100, "Hund")):
        r = out.get(f"{fw}_5m_{nb}")
        for core, csh in CORES:
            ce = (cores[core].get(nb) or {}).get("sdf") if nb in cores[core] else None
            if nb == 16: ce = (D.get(core, {}).get("event_sdf") or {}).get("energy_per_bin_nJ")   # no 16-bin core window: the 200-bin annotated one (nearest)
            mac(f"ratioW{wsh}{sh}{csh}", (r["energy_per_bin_nJ"] / ce) if (r and ce) else None, 4)
(ROOT / "results/explore").mkdir(exist_ok=True); json.dump(out, open(ROOT / "results/explore/software6.json", "w"), indent=1, default=float)
(ROOT / "paper/numbers_software6.tex").write_text("\n".join(M) + "\n")
for k, v in out.items():
    if k.endswith("_16") or k.endswith("_100"): print(k, {a: (round(b, 3) if isinstance(b, float) else b) for a, b in v.items() if a in ("n_bins", "events", "events_per_bin", "energy_per_bin_nJ", "cycles_per_bin")})
print("events per window:", EV); print("cores:", {k: {n: {a: (round(b, 3) if b else None) for a, b in vv.items()} for n, vv in v.items()} for k, v in cores.items()})
