#!/usr/bin/env python3
"""Round 5 (E7): software baseline on the VexRiscv SoC with the per-pin method over the decoding window, at 50 MHz (existing
waveforms) and 5 MHz (sky130_vex2_soc_5m hardening), for the released -O2 firmware and the hand-tuned firmware. Sources:
power/out_soc_<fw>_<clk>/{window.json, pwr/power_vcd.rpt (vdd-only SRAM liberty), asgen/power_vcd.rpt, idle/pwr/power_vcd.rpt}.
Writes results/explore/software5.json and paper/numbers_software5.tex (macros \\cpu<Fw><Clk>...), keeping the reference-flow
figures of sw/collect_software.py in paper/numbers_software.tex untouched."""
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from collect_results import parse_group_table, RATE
ROOT = Path(__file__).resolve().parent.parent
RUNS = {("o2", "50m"): ("Otwo", "Fifty", 20.0), ("tuned", "50m"): ("Tuned", "Fifty", 20.0), ("o2", "5m"): ("Otwo", "Five", 200.0), ("tuned", "5m"): ("Tuned", "Five", 200.0)}
out = {}; M = ["% auto-generated by sw/collect_software5.py (round 5, E7: per-pin method over the decoding window)"]
def f(x, nd=3): return "--" if x is None else (f"{x:,.0f}" if abs(x) >= 1000 else f"{x:.{nd}g}")
def mac(n, v, nd=3): M.append(f"\\newcommand{{\\{n}}}{{{f(v, nd)}}}")
D = json.load(open(ROOT / "results/designs.json"))
def core_e(name):
    d = D.get(name, {}); return (d.get("event_sdf") or d.get("event") or {}).get("energy_per_bin_nJ")
for (fw, clk), (shf, shc, T) in RUNS.items():
    base = ROOT / f"power/out_soc_{fw}_{clk}"
    if not (base / "pwr/power_vcd.rpt").exists(): continue
    w = json.load(open(base / "window.json")); g = parse_group_table(base / "pwr/power_vcd.rpt"); ga = parse_group_table(base / "asgen/power_vcd.rpt") if (base / "asgen/power_vcd.rpt").exists() else None
    cyc = w["cycles_in_window"]; nb = w["n_bins"]; Tw = cyc * T * 1e-9; P = g["Total"]["total"]
    r = {"firmware": fw, "clock_MHz": 1e3 / T, "cycles_per_bin": cyc / nb, "latency_us": cyc / nb * T * 1e-3, "power_window_mW": P * 1e3, "energy_per_bin_nJ": P * Tw / nb * 1e9,
         "energy_per_bin_asgen_nJ": (ga["Total"]["total"] * Tw / nb * 1e9) if ga else None, "leakage_uW": g["Total"]["leakage"] * 1e6,
         "groups_mW": {k: v["total"] * 1e3 for k, v in g.items() if k != "Total"}, "macro_uW": g.get("Macro", {}).get("total", 0) * 1e6}
    if (base / "idle/pwr/power_vcd.rpt").exists():
        gi = parse_group_table(base / "idle/pwr/power_vcd.rpt"); r["idle_power_uW"] = gi["Total"]["total"] * 1e6     # clock running, core asleep (sram_clk_en low)
    E = r["energy_per_bin_nJ"]; leak = r["leakage_uW"]; idle = r.get("idle_power_uW")
    r["avg_power_uW_250Hz_clkstopped"] = E * RATE * 1e-3 + leak
    if idle is not None:
        r["avg_power_uW_250Hz_clkrunning"] = E * RATE * 1e-3 + idle
        r["avg_power_uW_250Hz_clk32k"] = E * RATE * 1e-3 + leak + max(idle - leak, 0) * (0.032768 / (1e3 / T))
    r["duty_250Hz"] = r["latency_us"] * 1e-6 * RATE
    out[f"{fw}_{clk}"] = r
    s = f"{shf}{shc}"
    mac(f"cycCpu{s}", r["cycles_per_bin"]); mac(f"latCpu{s}", r["latency_us"]); mac(f"pWinCpu{s}", r["power_window_mW"]); mac(f"eCpu{s}", E, 4); mac(f"eCpuAsgen{s}", r["energy_per_bin_asgen_nJ"], 4)
    mac(f"leakCpu{s}", leak); mac(f"idleCpu{s}", idle); mac(f"pAvgStopCpu{s}", r["avg_power_uW_250Hz_clkstopped"]); mac(f"pAvgRunCpu{s}", r.get("avg_power_uW_250Hz_clkrunning"))
    mac(f"pAvgSlowCpu{s}", r.get("avg_power_uW_250Hz_clk32k")); mac(f"macroCpu{s}", r["macro_uW"]); mac(f"dutyCpu{s}Pct", r["duty_250Hz"] * 100)
    for core, csh in (("bmi_snn_sp", "Sp"), ("bmi_snn_m12", "Iso"), ("bmi_snn_min32", "MinH"), ("bmi_snn_top", "Seq")):
        ec = core_e(core); mac(f"ratioCpu{s}{csh}", (E / ec) if ec else None)
for fw in ("o2", "tuned"):
    a, b = out.get(f"{fw}_50m"), out.get(f"{fw}_5m")
    if a and b: mac(f"eCpu{'Otwo' if fw == 'o2' else 'Tuned'}FiveOverFifty", b["energy_per_bin_nJ"] / a["energy_per_bin_nJ"])
try:
    ref = json.load(open(ROOT / "results/explore/software.json"))
    for fw, key in (("o2", "o2"), ("tuned", "_tuned")):
        r = out.get(f"{fw}_50m"); e_ref = (ref.get(key) or {}).get("energy_per_bin_nJ_ref")
        if r and e_ref: r["energy_per_bin_nJ_reference_flow"] = e_ref; mac(f"methodRatioCpu{'Otwo' if fw == 'o2' else 'Tuned'}", r["energy_per_bin_nJ"] / e_ref)
except Exception: pass
json.dump(out, open(ROOT / "results/explore/software5.json", "w"), indent=1)
(ROOT / "paper/numbers_software5.tex").write_text("\n".join(M) + "\n")
for k, r in out.items(): print(f"{k:10s} cyc/bin {r['cycles_per_bin']:8.1f} P_win {r['power_window_mW']:7.3f} mW E {r['energy_per_bin_nJ']:8.1f} nJ (asgen {f(r['energy_per_bin_asgen_nJ'])}) leak {r['leakage_uW']:.2f} uW idle {f(r.get('idle_power_uW'))} uW P_avg stop {r['avg_power_uW_250Hz_clkstopped']:.1f} run {f(r.get('avg_power_uW_250Hz_clkrunning'))} uW")
