#!/usr/bin/env python3
"""Round 5 (E3): per-session netlists. For sp, min32 and m12 the cores hardened with the weights of indy_20160622_01 (*_s622) and
indy_20170131_02 (*_s131) are measured on their own session's full test block (zero-delay) and 5,000-bin annotated window,
next to the main core (weights of indy_20160630_01). Compares with the transfer model of the previous rounds (energy predicted from
the session's event rate). Writes results/per_session.csv and paper/numbers_persession.tex."""
import json, csv
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
D = json.load(open(ROOT / "results/designs.json"))
SESS = {"A": "indy_20160622_01", "B": "indy_20160630_01", "C": "indy_20170131_02"}
CORES = {"sp": ("Sp", {"A": "bmi_snn_sp_s622", "B": "bmi_snn_sp", "C": "bmi_snn_sp_s131"}),
         "min32": ("MinH", {"A": "bmi_snn_min32_s622", "B": "bmi_snn_min32", "C": "bmi_snn_min32_s131"}),
         "g32p50": ("GcHalf", {"A": "bmi_snn_g32p50_s622", "B": "bmi_snn_g32p50", "C": "bmi_snn_g32p50_s131"}),   # round 6 (E4a)
         "m12": ("MinT", {"A": "bmi_snn_m12_s622", "B": "bmi_snn_m12", "C": "bmi_snn_m12_s131"})}
try: TR = json.load(open(ROOT / "results/explore/transfer.json"))      # transfer model of the previous rounds (if present)
except Exception: TR = {}
rows = []; M = ["% auto-generated by sw/collect_persession.py (round 5, E3)"]
def f(x, nd=3): return "" if x is None else f"{x:.{nd}g}"
def mac(n, v, nd=3): M.append(f"\\newcommand{{\\{n}}}{{{'--' if v is None else (f'{v:,.0f}' if abs(v) >= 1000 else f'{v:.{nd}g}')}}}")
for core, (sh, per) in CORES.items():
    for ss, dname in per.items():
        s = SESS[ss]; d = D.get(dname, {}); fb = d.get("full", {}).get(s, {}); e500 = d.get("event", {}); p = d.get("pnr", {})
        fu = fb.get("func", {}); sd = fb.get("sdf", {})
        row = {"core": core, "session": s, "design": dname, "util_pct": p.get("util_target_pct"), "area_mm2": (p.get("instance_area_um2") or 0) / 1e6 or None, "cells": p.get("stdcells"),
               "r2_int": d.get("r2"), "bins_full": fu.get("tb", {}).get("bins"), "events_per_bin_full": (fu["tb"]["events"] / fu["tb"]["bins"]) if fu.get("tb", {}).get("bins") else None,
               "energy_per_bin_full_nJ": fu.get("energy_per_bin_nJ"), "cycles_per_bin_full": fu.get("cycles_per_bin"),
               "bins_sdf": sd.get("tb", {}).get("bins"), "energy_per_bin_sdf_nJ": sd.get("energy_per_bin_nJ"),
               "energy_per_bin_500win_nJ": e500.get("energy_per_bin_nJ") if ss == "B" else None, "leakage_uW": d.get("idle", {}).get("leakage_uW"),
               "transfer_model_nJ": ((TR.get(dname if ss == "B" else per["B"]) or {}).get("e_at_session_mean") or {}).get({"A": "SessA", "B": "SessRef", "C": "SessB"}[ss]),   # 50 MHz transfer model of the previous rounds, at the whole-session mean rate
               "bit_exact": fu.get("pass")}
        rows.append(row)
        mac(f"ePerSess{sh}{ss}", row["energy_per_bin_full_nJ"]); mac(f"ePerSessSdf{sh}{ss}", row["energy_per_bin_sdf_nJ"]); mac(f"evPerSess{sh}{ss}", row["events_per_bin_full"])
        mac(f"nbPerSess{sh}{ss}", row["bins_full"], 6); mac(f"areaPerSess{sh}{ss}", row["area_mm2"]); mac(f"utilPerSess{sh}{ss}", row["util_pct"], 2); mac(f"rsqPerSess{sh}{ss}", row["r2_int"])
    es = [r["energy_per_bin_full_nJ"] for r in rows if r["core"] == core]
    if all(x is not None for x in es) and es: mac(f"ePerSessMean{sh}", sum(es) / len(es)); mac(f"ePerSessSpread{sh}", (max(es) - min(es)) / (sum(es) / len(es)) * 100)
with open(ROOT / "results/per_session.csv", "w", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=list(rows[0].keys())); w.writeheader()
    for r in rows: w.writerow({k: (f(v) if isinstance(v, float) else v) for k, v in r.items()})
(ROOT / "paper/numbers_persession.tex").write_text("\n".join(M) + "\n")
for r in rows: print(f"{r['core']:6s} {r['session']} {r['design']:20s} util={r['util_pct']} E_full={f(r['energy_per_bin_full_nJ'])} nJ ({r['bins_full']} bins, {f(r['events_per_bin_full'])} ev/bin) E_sdf={f(r['energy_per_bin_sdf_nJ'])} transfer={f(r['transfer_model_nJ'])} exact={r['bit_exact']}")
