#!/usr/bin/env python3
"""E2: seed statistics of the reported configurations. Reads train.json of the seed-0 models (released names) and of the
seed-1..4 models (suffix _s<seed>), writes results/seeds.json, paper/seeds_table.tex and paper/numbers_seeds.tex."""
from __future__ import annotations
import json, sys
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent
SESS = ["indy_20160622_01", "indy_20160630_01", "indy_20170131_02"]
CONFIGS = [  # label, model tag without session prefix, macro suffix
    ("$H{=}64$, dense", "H64_th256_k44_drop", "HsfDense"),
    ("$H{=}64$, 50\\,\\% synapses", "H64_th256_k44_drop_p0.5", "HsfHalf"),
    ("$H{=}64$, 25\\,\\% synapses", "H64_th256_k44_drop_p0.25", "HsfQuarter"),
    ("$H{=}64$, 12.5\\,\\% synapses", "H64_th256_k44_drop_p0.125", "HsfEighth"),
    ("$H{=}32$, dense", "H32_th256_k44_drop", "HtDense"),
    ("$H{=}16$, dense", "H16_th256_k44_drop", "HsDense"),
]
SEEDS = [0, 1, 2, 3, 4]
def r2(sess, tag, seed):
    d = ROOT / "results/models" / (f"{sess}_{tag}" if seed == 0 else f"{sess}_{tag}_s{seed}")
    f = d / "train.json"
    if not f.exists(): return None
    return json.load(open(f))["test_r2"]
out = {}; rows = []; M = []
def f3(x): return "--" if x is None else f"{x:.3f}"
for label, tag, sh in CONFIGS:
    per_seed_mean = []; per_sess = {}
    for seed in SEEDS:
        vals = [r2(s, tag, seed) for s in SESS]
        if all(v is not None for v in vals): per_seed_mean.append(float(np.mean(vals)))
        for s, v in zip(SESS, vals):
            if v is not None: per_sess.setdefault(s, []).append(v)
    n = len(per_seed_mean)
    mean = float(np.mean(per_seed_mean)) if n else None; sd = float(np.std(per_seed_mean, ddof=1)) if n > 1 else None
    mn = float(np.min(per_seed_mean)) if n else None; mx = float(np.max(per_seed_mean)) if n else None
    out[tag] = {"label": label, "n_seeds": n, "mean_r2_per_seed": per_seed_mean, "mean": mean, "sd": sd, "min": mn, "max": mx,
                "per_session": {s: {"mean": float(np.mean(v)), "sd": float(np.std(v, ddof=1)) if len(v) > 1 else None, "n": len(v)} for s, v in per_sess.items()},
                "seed0": r2(SESS[0], tag, 0) and float(np.mean([r2(s, tag, 0) for s in SESS]))}
    sess_cells = [f"{f3(out[tag]['per_session'][s]['mean'])} $\\pm$ {f3(out[tag]['per_session'][s]['sd'])}" if s in out[tag]["per_session"] and out[tag]["per_session"][s]["sd"] is not None else f3(out[tag]['per_session'].get(s, {}).get('mean')) for s in SESS]
    rows.append(f"{label} & {n} & " + " & ".join(sess_cells) + f" & {f3(mean)} $\\pm$ {f3(sd)} & {f3(mn)}--{f3(mx)} \\\\")
    for k, v in (("Mean", mean), ("Sd", sd), ("Min", mn), ("Max", mx), ("SeedZero", out[tag]["seed0"])):
        M.append(f"\\newcommand{{\\r{sh}{k}}}{{{f3(v)}}}")
    M.append(f"\\newcommand{{\\n{sh}}}{{{n}}}")
(ROOT / "results/seeds.json").write_text(json.dumps(out, indent=1))
hdr = "Configuration & seeds & \\texttt{20160622\\_01} & \\texttt{20160630\\_01} & \\texttt{20170131\\_02} & mean of sessions & range \\\\"
(ROOT / "paper/seeds_table.tex").write_text("\\begin{tabular}{@{}lc lll ll@{}}\n\\toprule\n" + hdr + "\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}%\n")
(ROOT / "paper/numbers_seeds.tex").write_text("% auto-generated by sw/collect_seeds.py\n" + "\n".join(M) + "\n")
for tag, d in out.items(): print(f"{d['label']:32s} n={d['n_seeds']}  mean {f3(d['mean'])} sd {f3(d['sd'])}  range {f3(d['min'])}-{f3(d['max'])}")
