#!/usr/bin/env python3
"""Round 5 (E2): accuracy-energy Pareto table of the training grid. One row per configuration (H, synapse density):
integer-reference R2 (eval_int.json) of the five seeds on the three sessions (mean, sd over seeds of the session mean), the R2 of
the seed-0 model on indy_20160630_01 (the model that is hardened), and the hardware figures of the 12-bit gated hardwired core of
that model at 5 MHz from results/designs.json (energy per bin zero-delay and annotated, leakage, area, cells, P_avg at 250 bins/s).
Writes results/pareto.csv and paper/numbers_pareto.tex."""
import json, csv, sys
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent
SESS = ["indy_20160622_01", "indy_20160630_01", "indy_20170131_02"]
GRID = [  # tag, H, density, hardened core (12-bit gated hardwired), macro suffix
    ("H128_th256_k44_drop", 128, 1.0, "bmi_snn_g128", "GaDense"), ("H128_th256_k44_drop_p0.25", 128, 0.25, "bmi_snn_g128p25", "GaQuarter"),
    ("H128_th256_k44_drop_p0.125", 128, 0.125, "bmi_snn_g128p125", "GaEighth"),
    ("H64_th256_k44_drop", 64, 1.0, "bmi_snn_m12", "MinT"), ("H64_th256_k44_drop_p0.5", 64, 0.5, "bmi_snn_g64p50", "GbHalf"),
    ("H64_th256_k44_drop_p0.25", 64, 0.25, "bmi_snn_sp", "Sp"), ("H64_th256_k44_drop_p0.125", 64, 0.125, "bmi_snn_g64p125", "GbEighth"),
    ("H32_th256_k44_drop", 32, 1.0, "bmi_snn_min32", "MinH"), ("H32_th256_k44_drop_p0.5", 32, 0.5, "bmi_snn_g32p50", "GcHalf"),
    ("H32_th256_k44_drop_p0.25", 32, 0.25, "bmi_snn_g32p25", "GcQuarter"),
    ("H16_th256_k44_drop", 16, 1.0, "bmi_snn_min16", "MinS"), ("H16_th256_k44_drop_p0.5", 16, 0.5, "bmi_snn_g16p50", "GdHalf"),
    # round 6 (E4d): four more grid points
    ("H48_th256_k44_drop", 48, 1.0, "bmi_snn_g48", "GeDense"), ("H48_th256_k44_drop_p0.5", 48, 0.5, "bmi_snn_g48p50", "GeHalf"),
    ("H48_th256_k44_drop_p0.25", 48, 0.25, "bmi_snn_g48p25", "GeQuarter"), ("H32_th256_k44_drop_p0.125", 32, 0.125, "bmi_snn_g32p125", "GcEighth"),
]
D = json.load(open(ROOT / "results/designs.json"))
def r2_int(sess, tag, seed):
    d = ROOT / "results/models" / (f"{sess}_{tag}" if seed == 0 else f"{sess}_{tag}_s{seed}") / "eval_int.json"
    return json.load(open(d))["test_r2_int"] if d.exists() else None
def r2_float(sess, tag, seed):
    d = ROOT / "results/models" / (f"{sess}_{tag}" if seed == 0 else f"{sess}_{tag}_s{seed}") / "train.json"
    return json.load(open(d))["test_r2"] if d.exists() else None
rows = []; M = ["% auto-generated by sw/collect_pareto.py (round 5, E2)"]
from fmt3 import sig as _sig
def f(x, nd=3): return _sig(x, nd, none="").replace(",", "")   # round 7 (CSV cells: no thousands separators)
def mac(n, v, nd=3): M.append(f"\\newcommand{{\\{n}}}{{{_sig(v, nd)}}}")
for tag, H, dens, core, sh in GRID:
    seed_means = []; per_sess = {s: [] for s in SESS}
    for seed in range(5):
        v = [r2_int(s, tag, seed) for s in SESS]
        if all(x is not None for x in v): seed_means.append(float(np.mean(v)))
        for s, x in zip(SESS, v):
            if x is not None: per_sess[s].append(x)
    n = len(seed_means); mean = float(np.mean(seed_means)) if n else None; sd = float(np.std(seed_means, ddof=1)) if n > 1 else None
    fl = [r2_float(s, tag, 0) for s in SESS]; fl_mean = float(np.mean(fl)) if all(x is not None for x in fl) else None
    hw = D.get(core, {}); e = hw.get("event", {}); es = hw.get("event_sdf", {}); i = hw.get("idle", {}); p = hw.get("pnr", {})
    row = {"tag": tag, "H": H, "density": dens, "core": core, "n_seeds": n, "r2_int_mean": mean, "r2_int_sd": sd,
           "r2_int_min": float(np.min(seed_means)) if n else None, "r2_int_max": float(np.max(seed_means)) if n else None,
           "r2_int_seed0_B": r2_int("indy_20160630_01", tag, 0), "r2_float_seed0_mean": fl_mean,
           "energy_per_bin_nJ": e.get("energy_per_bin_nJ"), "energy_per_bin_sdf_nJ": es.get("energy_per_bin_nJ"), "cycles_per_bin": e.get("cycles_per_bin"),
           "leakage_uW": i.get("leakage_uW"), "area_mm2": (p.get("instance_area_um2") or 0) / 1e6 or None, "cells": p.get("stdcells"), "util_pct": p.get("util_target_pct"),
           "p_avg_250Hz_uW": hw.get("avg_power_uW_250Hz_clkstopped_sdf") or hw.get("avg_power_uW_250Hz_clkstopped")}
    for s in SESS: row[f"r2_int_{s}_mean"] = float(np.mean(per_sess[s])) if per_sess[s] else None; row[f"r2_int_{s}_sd"] = float(np.std(per_sess[s], ddof=1)) if len(per_sess[s]) > 1 else None
    rows.append(row)
    mac(f"rsqGrid{sh}", mean); mac(f"rsqGridSd{sh}", sd); mac(f"rsqGridB{sh}", row["r2_int_seed0_B"]); mac(f"nSeedsGrid{sh}", n, 1)
    mac(f"eGrid{sh}", row["energy_per_bin_nJ"]); mac(f"eGridSdf{sh}", row["energy_per_bin_sdf_nJ"]); mac(f"pavgGrid{sh}", row["p_avg_250Hz_uW"]); mac(f"areaGrid{sh}", row["area_mm2"])
# Pareto front on (energy, accuracy): configurations not dominated (lower energy and higher mean R2 by another)
have = [r for r in rows if r["energy_per_bin_nJ"] is not None and r["r2_int_mean"] is not None]
for r in rows:
    r["pareto"] = (r in have) and not any((o["energy_per_bin_nJ"] <= r["energy_per_bin_nJ"] and o["r2_int_mean"] >= r["r2_int_mean"] and o is not r) for o in have)
with open(ROOT / "results/pareto.csv", "w", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=list(rows[0].keys())); w.writeheader()
    for r in rows: w.writerow({k: (f(v) if isinstance(v, float) else v) for k, v in r.items()})
(ROOT / "paper/numbers_pareto.tex").write_text("\n".join(M) + "\n")
for r in rows: print(f"{r['tag']:30s} H={r['H']:3d} d={r['density']:<5} seeds={r['n_seeds']} R2={f(r['r2_int_mean'])}+-{f(r['r2_int_sd'])} (B seed0 {f(r['r2_int_seed0_B'])}) E={f(r['energy_per_bin_nJ'])} nJ Esdf={f(r['energy_per_bin_sdf_nJ'])} Pavg={f(r['p_avg_250Hz_uW'])} uW pareto={r['pareto']}")
