#!/usr/bin/env python3
"""Linear leaky-integrator baseline (train_snn.py --linear: 96 x 2 weights, two leaky accumulators, no hidden layer) against the
integer SNN and the NeuroBench ANN 2D baseline, per Indy session. Writes results/explore/linear.json and paper/numbers_linear.tex."""
import json
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent
SESS = ["indy_20160622_01", "indy_20160630_01", "indy_20170131_02"]; SH = ["A", "B", "C"]
nb = json.load(open(ROOT / "results/explore/neurobench_baselines.json"))
out = {}; M = ["% auto-generated by sw/collect_linear.py"]; lin = []
for s, sh in zip(SESS, SH):
    f = ROOT / "results/models" / f"{s}_LIN_k4_drop/eval_int.json"
    if f.exists():
        e = json.load(open(f)); lin.append(e["test_r2_int"]); out[s] = {"r2_int_linear": e["test_r2_int"], "ann2d": nb["ANN2D"][s]}
        M.append(f"\\newcommand{{\\rTwoLin{sh}}}{{{e['test_r2_int']:.3f}}}")
    else: M.append(f"\\newcommand{{\\rTwoLin{sh}}}{{--}}")
    M.append(f"\\newcommand{{\\nbAnnTwo{sh}}}{{{nb['ANN2D'][s]:.3f}}}")
M.append(f"\\newcommand{{\\rTwoLinMean}}{{{np.mean(lin):.3f}}}" if len(lin) == 3 else "\\newcommand{\\rTwoLinMean}{--}")
M.append(f"\\newcommand{{\\nbAnnTwoMean}}{{{nb['ANN2D']['indy_mean']:.3f}}}")
for s, sh in zip(["loco_20170210_03", "loco_20170215_02", "loco_20170301_05"], ["LocoA", "LocoB", "LocoC"]):
    M.append(f"\\newcommand{{\\nbAnnTwo{sh}}}{{{nb['ANN2D'][s]:.3f}}}")
M.append(f"\\newcommand{{\\nbAnnTwoLocoMean}}{{{nb['ANN2D']['loco_mean']:.3f}}}")
snn = [json.load(open(ROOT / "results/models" / f"{s}_H64_th256_k44_drop/eval_int.json"))["test_r2_int"] for s in SESS]
if len(lin) == 3: M.append(f"\\newcommand{{\\rTwoLinGap}}{{{np.mean(snn) - np.mean(lin):.2f}}}")   # what the hidden layer buys in mean R2
else: M.append("\\newcommand{\\rTwoLinGap}{--}")
(ROOT / "results/explore/linear.json").write_text(json.dumps(out, indent=1)); (ROOT / "paper/numbers_linear.tex").write_text("\n".join(M) + "\n")
print(out, "mean linear", round(float(np.mean(lin)), 3) if lin else None, "mean SNN", round(float(np.mean(snn)), 3))
