#!/usr/bin/env python3
"""E11 (software): recalibration with hardwired input weights. W1 of session A frozen, bias row + read-out (W2, g, b) retrained
on session B (results/models/<B>_H64_th256_k44_drop_adaptW1from_<A>), against full training on B (seed 0)."""
import json
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent
SESS = ["indy_20160622_01", "indy_20160630_01", "indy_20170131_02"]
full = {s: json.load(open(ROOT / "results/models" / f"{s}_H64_th256_k44_drop/train.json"))["test_r2"] for s in SESS}
out = {"full": full, "adapt": {}}; vals = []; losses = []
for a in SESS:
    for b in SESS:
        if a == b: continue
        f = ROOT / "results/models" / f"{b}_H64_th256_k44_adaptW1from_{a[5:]}/train.json"
        if not f.exists(): continue
        r = json.load(open(f))["test_r2"]; out["adapt"][f"{a[5:]}->{b[5:]}"] = r; vals.append(r); losses.append(full[b] - r)
out["n"] = len(vals); out["adapt_min"] = min(vals) if vals else None; out["adapt_max"] = max(vals) if vals else None
out["adapt_mean"] = float(np.mean(vals)) if vals else None; out["loss_mean"] = float(np.mean(losses)) if losses else None
(ROOT / "results/explore/adapt.json").write_text(json.dumps(out, indent=1))
f3 = lambda x: "--" if x is None else f"{x:.2f}"
M = ["% auto-generated by sw/collect_adapt.py", f"\\newcommand{{\\adaptN}}{{{out['n']}}}", f"\\newcommand{{\\adaptMin}}{{{f3(out['adapt_min'])}}}",
     f"\\newcommand{{\\adaptMax}}{{{f3(out['adapt_max'])}}}", f"\\newcommand{{\\adaptMean}}{{{f3(out['adapt_mean'])}}}", f"\\newcommand{{\\adaptLossMean}}{{{f3(out['loss_mean'])}}}"]
(ROOT / "paper/numbers_adapt.tex").write_text("\n".join(M) + "\n")
print(out["adapt"], "mean", f3(out["adapt_mean"]), "full", {k: round(v, 3) for k, v in full.items()})
