#!/usr/bin/env python3
"""Round 5 (E4): transfer across sessions at 5 MHz for the programmable cores (weights of each session loaded): energy per bin
against events per bin over the full block of indy_20160630_01 and the 20,000-bin windows of the other two sessions, linear model
E_bin = a + b * n_ev, residual. For the hardwired cores the per-session netlists (E3, sw/collect_persession.py) take this role.
Writes results/explore/transfer5.json and paper/numbers_transfer5.tex."""
import json
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent
D = json.load(open(ROOT / "results/designs.json"))
SESS = ["indy_20160622_01", "indy_20160630_01", "indy_20170131_02"]; SH = {"indy_20160622_01": "A", "indy_20160630_01": "Ref", "indy_20170131_02": "B"}
out = {}; M = ["% auto-generated by sw/collect_transfer5.py (round 5, E4: 5 MHz full blocks / 20k-bin windows)"]
def f(x, nd=3): return "--" if x is None else f"{x:.{nd}g}"
for name, sh in (("bmi_snn_top", "Seq"), ("bmi_snn_topg", "SeqG"), ("bmi_snn_lmin2", "LmMinP"), ("bmi_snn_lmem2", "LmP")):
    d = D.get(name, {}); pts = []
    for s in SESS:
        fu = d.get("full", {}).get(s, {}).get("func")
        if fu: pts.append((fu["tb"]["events"] / fu["tb"]["bins"], fu["energy_per_bin_nJ"], fu["cycles_per_bin"], fu["tb"]["bins"], SH[s]))
    o = {"points": [dict(ev_per_bin=p[0], e_nJ=p[1], cyc=p[2], bins=p[3], stream=p[4]) for p in pts]}
    if len(pts) >= 2:
        x = np.array([p[0] for p in pts]); y = np.array([p[1] for p in pts]); b, a = np.polyfit(x, y, 1)
        o.update(intercept_nJ=float(a), slope_nJ_per_event=float(b), resid_max_nJ=float(np.max(np.abs(y - (a + b * x)))), resid_max_pct=float(np.max(np.abs(y - (a + b * x)) / y) * 100))
        M += [f"\\newcommand{{\\xferFive{sh}Intercept}}{{{a:.3g}}}", f"\\newcommand{{\\xferFive{sh}Slope}}{{{b:.3g}}}", f"\\newcommand{{\\xferFive{sh}Resid}}{{{o['resid_max_nJ']:.2g}}}", f"\\newcommand{{\\xferFive{sh}ResidPct}}{{{o['resid_max_pct']:.2g}}}"]
    for p in pts: M += [f"\\newcommand{{\\xferFive{sh}Ev{p[4]}}}{{{p[0]:.3g}}}", f"\\newcommand{{\\xferFive{sh}E{p[4]}}}{{{p[1]:.3g}}}", f"\\newcommand{{\\xferFive{sh}Nb{p[4]}}}{{{p[3]:,}}}"]
    out[name] = o; print(name, o)
(ROOT / "results/explore/transfer5.json").write_text(json.dumps(out, indent=1)); (ROOT / "paper/numbers_transfer5.tex").write_text("\n".join(M) + "\n")
