#!/usr/bin/env python3
"""E9: energy per bin of the sequential SRAM core and the pruned core on the streams of all three sessions (weights of
indy_20160630_01), and the linear model E_bin = a + b * n_ev fitted through the three windows. Reads the functional runs
<design>_md0_full (630 stream) and <design>_md0_x<session> (other streams) via results/designs.json."""
import json
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parent.parent
D = json.load(open(ROOT / "results/designs.json"))
SESS = {"SessA": 7.69, "SessRef": 5.27, "SessB": 3.95}   # whole-session mean active channels per bin (20160622_01, 20160630_01, 20170131_02)
out = {}; M = ["% auto-generated by sw/collect_transfer.py"]
for name, sh in (("bmi_snn_top", "Seq"), ("bmi_snn_sp", "Sp")):
    d = D.get(name, {}); pts = []
    for key, lab in (("event", "Ref"), ("event_x20160622_01", "A"), ("event_x20170131_02", "B")):   # Ref = indy_20160630_01 stream, A = 20160622_01, B = 20170131_02
        r = d.get(key)
        if r: pts.append((r["tb"]["events"] / r["tb"]["bins"], r["energy_per_bin_nJ"], r["cycles_per_bin"], lab))
    o = {"points": [dict(ev_per_bin=p[0], e_nJ=p[1], cyc=p[2], stream=p[3]) for p in pts]}
    if len(pts) >= 2:
        x = np.array([p[0] for p in pts]); y = np.array([p[1] for p in pts]); b, a = np.polyfit(x, y, 1)
        o.update(intercept_nJ=float(a), slope_nJ_per_event=float(b), resid_max_nJ=float(np.max(np.abs(y - (a + b * x)))))
        o["e_at_session_mean"] = {s: float(a + b * v) for s, v in SESS.items()}
        M += [f"\\newcommand{{\\xfer{sh}Intercept}}{{{a:.3g}}}", f"\\newcommand{{\\xfer{sh}Slope}}{{{b:.3g}}}", f"\\newcommand{{\\xfer{sh}Resid}}{{{o['resid_max_nJ']:.2g}}}"]
        for s, v in o["e_at_session_mean"].items(): M.append(f"\\newcommand{{\\xfer{sh}E{s}}}{{{v:.3g}}}")
    for p in pts: M += [f"\\newcommand{{\\xfer{sh}Ev{p[3]}}}{{{p[0]:.3g}}}", f"\\newcommand{{\\xfer{sh}E{p[3]}}}{{{p[1]:.3g}}}"]
    out[name] = o; print(name, o)
for s, v in SESS.items(): M.append(f"\\newcommand{{\\xferRate{s}}}{{{v:.2f}}}")   # whole-session mean active channels per bin (Table 2)
(ROOT / "results/explore/transfer.json").write_text(json.dumps(out, indent=1))
(ROOT / "paper/numbers_transfer.tex").write_text("\n".join(M) + "\n")
