#!/usr/bin/env python3
"""Round 6 (E8, optional): utilization sweep of the pruned core on ASAP7 SRAM-Vt (40 / 50 / 60 (accepted policy run) / 70 %).
Sources: OpenROAD-flow-scripts logs/asap7/bmi_snn_sp_5m_sram[_sweep]_u<U>/base/{6_report.json,5_2_route.json}; per-pin power of the
same window (sim/measure_pdk5.sh asap7sram sp func with RUN_NICK=<nick> TAG_SFX=_u<U>): power/out_vcd_pdk5_asap7sram_sp[_u<U>]_{md0,idle}_full.
Writes results/asap7_util_sweep.csv and paper/numbers_sweep6.tex (\\sweepAsapS<Util><key>: area, cells, fill, setup, hold, drc, e, leak, pavg)."""
import json, csv, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from collect_results import parse_group_table, RATE
ROOT = Path(__file__).resolve().parent.parent; ORFS = Path("/media/pdk/OpenROAD-flow-scripts/flow"); TU = 1e-12; TCLK_PS = 200000
def f(x, nd=3): return "--" if x is None else (f"{x:,.0f}" if abs(x) >= 1000 else f"{x:.{nd}g}")
rows = []; M = ["% auto-generated by sw/collect_util_sweep6.py (round 6, E8: ASAP7 SRAM-Vt utilization sweep of the pruned core)"]
WORDS = {40: "Forty", 50: "Fifty", 60: "Sixty", 70: "Seventy"}
for U in (40, 50, 60, 70):
    nick = "bmi_snn_sp_5m_sram_u60" if U == 60 else f"bmi_snn_sp_5m_sram_sweep_u{U}"
    L = ORFS / "logs/asap7" / nick / "base"; r = dict(util=U, nick=nick, source="policy (accepted)" if U == 60 else "sweep")
    if (L / "6_report.json").exists():
        m = json.load(open(L / "6_report.json"))
        r.update(area_um2=m.get("finish__design__instance__area__stdcell"), cells=m.get("finish__design__instance__count__stdcell"),
                 fill_cells=m.get("finish__design__instance__count__class:fill_cell"), setup_ws_ns=(m.get("finish__timing__setup__ws") or 0) * TU * 1e9 if m.get("finish__timing__setup__ws") is not None else None,
                 hold_viol=m.get("finish__timing__drv__hold_violation_count"), core_area_um2=m.get("finish__design__core__area"))
    if (L / "5_2_route.json").exists(): r["drc"] = json.load(open(L / "5_2_route.json")).get("detailedroute__route__drc_errors")
    sfx = "" if U == 60 else f"_u{U}"
    ev = ROOT / f"power/out_vcd_pdk5_asap7sram_sp{sfx}_md0_full/power_vcd.rpt"; idle = ROOT / f"power/out_vcd_pdk5_asap7sram_sp{sfx}_idle_full/power_vcd.rpt"
    vv = ROOT / f"sim/build_pdk5_asap7sram_sp{sfx}_md0_full/vvp.log"
    if ev.exists() and idle.exists() and vv.exists():
        import re
        s = re.search(r"SUMMARY: bins=(\d+) events=(\d+) errors=(\d+) cycles=(\d+)", vv.read_text()); bins, ev_n, err, cyc = map(int, s.groups())
        P = parse_group_table(ev)["Total"]["total"]; lk = parse_group_table(idle)["Total"]["leakage"]
        r.update(bins=bins, cycles_per_bin=cyc / bins, power_avg_uW=P * 1e6, energy_per_bin_nJ=P * cyc * TCLK_PS * 1e-12 / bins * 1e9, leakage_uW=lk * 1e6, pass_=(err == 0))
        r["avg_power_uW_250Hz_clkstopped"] = r["energy_per_bin_nJ"] * RATE * 1e-3 + r["leakage_uW"]
    rows.append(r); w = WORDS[U]
    for k, v in (("area", (r.get("area_um2") or 0) / 1e6 or None), ("cells", r.get("cells")), ("fill", r.get("fill_cells")), ("setup", r.get("setup_ws_ns")), ("drc", r.get("drc")),
                 ("e", r.get("energy_per_bin_nJ")), ("leak", r.get("leakage_uW")), ("pavg", r.get("avg_power_uW_250Hz_clkstopped"))):
        M.append(f"\\newcommand{{\\sweepAsapS{w}{k}}}{{{f(v, 4 if k in ('cells', 'fill', 'setup') else 3)}}}")
keys = ["util", "nick", "source", "area_um2", "core_area_um2", "cells", "fill_cells", "setup_ws_ns", "hold_viol", "drc", "bins", "cycles_per_bin", "energy_per_bin_nJ", "leakage_uW", "avg_power_uW_250Hz_clkstopped", "pass_"]
with open(ROOT / "results/asap7_util_sweep.csv", "w", newline="") as fh:
    wr = csv.DictWriter(fh, fieldnames=keys, extrasaction="ignore"); wr.writeheader(); wr.writerows(rows)
(ROOT / "paper/numbers_sweep6.tex").write_text("\n".join(M) + "\n")
for r in rows: print({k: (round(v, 4) if isinstance(v, float) else v) for k, v in r.items() if k in ("util", "area_um2", "cells", "setup_ws_ns", "drc", "energy_per_bin_nJ", "leakage_uW", "avg_power_uW_250Hz_clkstopped")})
