#!/usr/bin/env python3
"""E4: software baseline variants on the VexRiscv SoC (compiler -O2 as released, -O3, hand-tuned inner loop).
Energy with the reference-flow method for all variants (P_awake x cycles per bin x 20 ns); the released -O2 figure in the
paper additionally has the per-pin VCD method (results.json). Writes results/explore/software.json, paper/numbers_software.tex."""
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from collect_results import parse_power_energy, TCLK_CPU_NS
ROOT = Path(__file__).resolve().parent.parent
V = {"": ("Otwo", "-O2 (released)"), "_o3": ("Othree", "-O3"), "_tuned": ("Tuned", "-O3, hand-tuned")}
D = json.load(open(ROOT / "results/designs.json")); R = json.load(open(ROOT / "results/results.json"))
e_seq = D["bmi_snn_top"]["event"]["energy_per_bin_nJ"]; e_sp = D["bmi_snn_sp"]["event"]["energy_per_bin_nJ"]
e_sp_sdf = D["bmi_snn_sp"].get("event_sdf", {}).get("energy_per_bin_nJ"); e_seq_sdf = D["bmi_snn_top"].get("event_sdf", {}).get("energy_per_bin_nJ")
out = {}; M = ["% auto-generated by sw/collect_software.py"]
def f(x, nd=3): return "--" if x is None else (f"{x:,.0f}" if abs(x) >= 1000 else f"{x:.{nd}g}")
for suf, (sh, label) in V.items():
    pe = ROOT / f"power/out_riscv{suf}/power_energy.txt"; cy = ROOT / f"results/riscv_cycles{suf}.json"
    if not (pe.exists() and cy.exists()): continue
    p = parse_power_energy(pe); txt = cy.read_text(); c = json.loads(txt[: txt.rfind("}") + 1])   # the cycle script also prints a 'wrote' line
    e_ref = p["power_awake_mW"] * 1e-3 * c["cycles_per_bin"] * TCLK_CPU_NS
    o = {"label": label, "cycles_per_bin": c["cycles_per_bin"], "power_awake_mW": p["power_awake_mW"], "energy_per_bin_nJ_ref": e_ref,
         "latency_us": c["cycles_per_bin"] * TCLK_CPU_NS * 1e-3}
    if suf == "": o["energy_per_bin_nJ_vcd"] = R["riscv"].get("energy_per_bin_nJ_vcd")
    idle = R["riscv"].get("idle_power_uW_50MHz"); leak = R["riscv"].get("leakage_uW")
    o["avg_power_uW_250Hz_clk"] = e_ref * 0.25 + (idle or 0); o["avg_power_uW_250Hz_leak"] = e_ref * 0.25 + (leak or 0)
    out[suf or "o2"] = o
    M += [f"\\newcommand{{\\cycCpu{sh}}}{{{f(o['cycles_per_bin'])}}}", f"\\newcommand{{\\pAwakeCpu{sh}}}{{{f(o['power_awake_mW'])}}}",
          f"\\newcommand{{\\eCpu{sh}Ref}}{{{f(e_ref)}}}", f"\\newcommand{{\\latCpu{sh}}}{{{f(o['latency_us'])}}}",
          f"\\newcommand{{\\ratioCpu{sh}Seq}}{{{f(e_ref / e_seq, 3)}}}", f"\\newcommand{{\\ratioCpu{sh}Sp}}{{{f(e_ref / e_sp, 3)}}}",
          f"\\newcommand{{\\pAvgCpu{sh}}}{{{f(o['avg_power_uW_250Hz_clk'])}}}", f"\\newcommand{{\\pAvgLeakCpu{sh}}}{{{f(o['avg_power_uW_250Hz_leak'])}}}"]
    if e_sp_sdf: M.append(f"\\newcommand{{\\ratioCpu{sh}SpSdf}}{{{f(e_ref / e_sp_sdf, 3)}}}")
    print(f"{label:18s} cycles/bin {o['cycles_per_bin']:8.1f}  P_awake {o['power_awake_mW']:.2f} mW  E {e_ref:7.0f} nJ  = {e_ref/e_seq:5.1f}x SRAM core, {e_ref/e_sp:5.0f}x pruned core")
if "o2" in out and "_tuned" in out:
    M.append(f"\\newcommand{{\\cpuTunedSpeedup}}{{{f(out['o2']['cycles_per_bin'] / out['_tuned']['cycles_per_bin'], 2)}}}")
    M.append(f"\\newcommand{{\\cpuTunedEnergyGain}}{{{f(out['o2']['energy_per_bin_nJ_ref'] / out['_tuned']['energy_per_bin_nJ_ref'], 2)}}}")
(ROOT / "results/explore/software.json").write_text(json.dumps(out, indent=1)); (ROOT / "paper/numbers_software.tex").write_text("\n".join(M) + "\n")
