#!/usr/bin/env python3
"""Round 5 (E14): the 1.28 V signoff. For sp, m12 and min32 at 5 MHz: (1) the tt-signoff hardening (<d>_5m) evaluated at
tt_025C_1v80 (its annotated 200-bin run) and re-evaluated at ss_n40C_1v28 (same activity, low-voltage liberty, worst setup slack);
(2) the hardening with ss_n40C_1v28 as signoff liberty (<d>_5m_lv, synthesis/harden_lowv.sh): cells, area, slacks at its corners,
energy of its own annotated run at ss_n40C_1v28 and its zero-delay/idle runs. Writes results/corners5.json, paper/corners_table5.tex,
paper/numbers_corners5.tex (macros \\cnrFive<Sh>...)."""
import json, re, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from collect_results import parse_group_table, parse_tb_summary, parse_metrics, RATE
from collect_designs import run_energy, run_idle
ROOT = Path(__file__).resolve().parent.parent
TCLK = 200.0
CORES = [("bmi_snn_sp", "Sp", "hardwired 12-bit, gated, 25\\,\\% synapses"), ("bmi_snn_m12", "MinT", "hardwired 12-bit, gated"), ("bmi_snn_min32", "MinH", "hardwired 16-bit, $H{=}32$")]
def f(x, nd=3): return "--" if x is None else (f"{x:,.0f}" if abs(x) >= 1000 else f"{x:.{nd}g}")
def slack_txt(d):
    p = ROOT / d / "slack.txt"
    if not p.exists(): return None, None
    v = dict(l.split() for l in p.read_text().split("\n") if l.strip())
    g = lambda k: float(v[k]) if k in v else None
    a, b = g("setup_ws") if "setup_ws" in v else g("setup_ws_ns"), g("hold_ws") if "hold_ws" in v else g("hold_ws_ns")
    if "setup_ws" in v: a = a * 1e9 if a is not None else None; b = b * 1e9 if b is not None else None      # seconds from sta::worst_slack_cmd
    return a, b
def energy_of(tag, rpt_dir):
    log = ROOT / f"sim/build_{tag}/vvp.log"; rpt = ROOT / rpt_dir / "power_vcd.rpt"
    if not (log.exists() and rpt.exists()): return None
    tb = parse_tb_summary(log); g = parse_group_table(rpt); t = log.read_text(errors="replace"); m = re.search(r"MEASURED: cycles_from_dump_start=(\d+)", t)
    cyc = int(m.group(1)) if m else tb.get("cycles")
    if not tb.get("bins"): return None
    return {"energy_per_bin_nJ": g["Total"]["total"] * cyc * TCLK * 1e-9 / tb["bins"] * 1e9, "power_uW": g["Total"]["total"] * 1e6, "leakage_uW": g["Total"]["leakage"] * 1e6, "bins": tb["bins"], "cycles": cyc}
out = {}; rows = []; M = ["% auto-generated by sw/collect_corners5.py (round 5, E14)"]
def mac(n, v, nd=3): M.append(f"\\newcommand{{\\{n}}}{{{f(v, nd)}}}")
for d, sh, label in CORES:
    r = {"label": label}
    mj = ROOT / f"synthesis/{d}/runs/{d}_5m/final/metrics.json"
    if mj.exists():
        p = parse_metrics(mj); m = json.load(open(mj)); r["tt"] = {"cells": p.get("stdcells"), "area_um2": p.get("instance_area_um2"), "setup_ws_ns": m.get("timing__setup__ws"), "hold_ws_ns": m.get("timing__hold__ws")}
        r["tt"]["e_tt"] = energy_of(f"{d}_5m_md0_sdf", f"power/out_vcd_{d}_5m_md0_sdf")
        e = energy_of(f"{d}_5m_md0_sdf", f"power/out_vcd_{d}_5m_md0_sdf_ss_n40C_1v28"); s_, h_ = slack_txt(f"power/out_vcd_{d}_5m_md0_sdf_ss_n40C_1v28")
        if e: e["setup_ws_ns"] = s_; e["hold_ws_ns"] = h_; e["fmax_MHz"] = (1e3 / (TCLK - s_)) if (s_ is not None and s_ < TCLK) else None
        r["tt"]["e_lowv"] = e
    mjl = ROOT / f"synthesis/{d}/runs/{d}_5m_lv/final/metrics.json"
    if mjl.exists():
        p = parse_metrics(mjl); m = json.load(open(mjl))
        r["lv"] = {"cells": p.get("stdcells"), "area_um2": p.get("instance_area_um2"), "setup_ws_ns": m.get("timing__setup__ws"), "hold_ws_ns": m.get("timing__hold__ws"),
                   "setup_ws_1v28_ns": m.get("timing__setup__ws__corner:nom_ss_n40C_1v28"), "hold_ws_1v28_ns": m.get("timing__hold__ws__corner:nom_ss_n40C_1v28"),
                   "setup_ws_tt_ns": m.get("timing__setup__ws__corner:nom_tt_025C_1v80"), "drc": m.get("route__drc_errors")}
        cu = ROOT / f"synthesis/{d}/config_lowv.yaml"; mu = re.search(r"^FP_CORE_UTIL:\s*(\d+)", cu.read_text(), flags=re.M) if cu.exists() else None; r["lv"]["util_pct"] = int(mu.group(1)) if mu else None
        r["lv"]["e_sdf_1v28"] = energy_of(f"{d}_5m_lv_md0_sdf", f"power/out_vcd_{d}_5m_lv_md0_sdf"); r["lv"]["e_func_1v28"] = energy_of(f"{d}_5m_lv_md0_full", f"power/out_vcd_{d}_5m_lv_md0_full")
        i = energy_of(f"{d}_5m_lv_idle_full", f"power/out_vcd_{d}_5m_lv_idle_full"); r["lv"]["leak_1v28_uW"] = i["leakage_uW"] if i else None
        if r["lv"]["e_sdf_1v28"] and r["lv"]["leak_1v28_uW"] is not None: r["lv"]["pavg_250Hz_uW"] = r["lv"]["e_sdf_1v28"]["energy_per_bin_nJ"] * RATE * 1e-3 + r["lv"]["leak_1v28_uW"]
    out[d] = r
    tt = r.get("tt", {}); lv = r.get("lv", {}); ett = (tt.get("e_tt") or {}); elv = (tt.get("e_lowv") or {}); es = (lv.get("e_sdf_1v28") or {})
    rows.append(f"{label} & {f(tt.get('cells'), 4)} & {f(ett.get('energy_per_bin_nJ'))} & {f(elv.get('energy_per_bin_nJ'))} & {f(elv.get('setup_ws_ns'), 4)} & {f(elv.get('fmax_MHz'))} & "
                f"{f(lv.get('util_pct'), 2)} & {f(lv.get('cells'), 4)} & {f(lv.get('setup_ws_1v28_ns'), 4)} & {f(lv.get('hold_ws_1v28_ns'), 3)} & {f(es.get('energy_per_bin_nJ'))} & {f(lv.get('leak_1v28_uW'))} & {f(lv.get('pavg_250Hz_uW'))} \\\\")
    mac(f"cnrFiveCellsTt{sh}", tt.get("cells"), 4); mac(f"cnrFiveETt{sh}", ett.get("energy_per_bin_nJ")); mac(f"cnrFiveELowVSwap{sh}", elv.get("energy_per_bin_nJ")); mac(f"cnrFiveSlackLowVSwap{sh}", elv.get("setup_ws_ns"), 4)
    mac(f"cnrFiveFmaxLowVSwap{sh}", elv.get("fmax_MHz")); mac(f"cnrFiveUtilLv{sh}", lv.get("util_pct"), 2); mac(f"cnrFiveCellsLv{sh}", lv.get("cells"), 4); mac(f"cnrFiveSlackLv{sh}", lv.get("setup_ws_1v28_ns"), 4)
    mac(f"cnrFiveHoldLv{sh}", lv.get("hold_ws_1v28_ns"), 3); mac(f"cnrFiveELv{sh}", es.get("energy_per_bin_nJ")); mac(f"cnrFiveLeakLv{sh}", lv.get("leak_1v28_uW")); mac(f"cnrFivePavgLv{sh}", lv.get("pavg_250Hz_uW"))
    mac(f"cnrFiveSlackTtOfLv{sh}", lv.get("setup_ws_tt_ns"), 4)
    if ett.get("energy_per_bin_nJ") and es.get("energy_per_bin_nJ"): mac(f"cnrFiveGainLv{sh}", ett["energy_per_bin_nJ"] / es["energy_per_bin_nJ"])
json.dump(out, open(ROOT / "results/corners5.json", "w"), indent=1)
hdr = "Core & \\multicolumn{5}{c}{TT signoff netlist (5 MHz)} & \\multicolumn{7}{c}{SS 1.28 V $-40\\,^{\\circ}$C signoff netlist} \\\\\n & cells & $E$ TT & $E$ 1.28 V & slack 1.28 V & $f_{\\max}$ 1.28 V & util. & cells & setup & hold & $E$ 1.28 V & leak. & $P_{\\mathrm{avg}}$ \\\\\n & & nJ & nJ & ns & MHz & \\% & & ns & ns & nJ & \\si{\\micro\\watt} & \\si{\\micro\\watt} \\\\"
(ROOT / "paper/corners_table5.tex").write_text("\\begin{tabular}{@{}l rrrrr rrrrrrr@{}}\n\\toprule\n" + hdr + "\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}%\n")
(ROOT / "paper/numbers_corners5.tex").write_text("\n".join(M) + "\n")
for d, r in out.items(): print(d, {k: (v if not isinstance(v, dict) else {kk: vv for kk, vv in v.items() if not isinstance(vv, dict)}) for k, v in r.items()})
