#!/usr/bin/env python3
"""Export bmi_weights.h (weights + token stream + expected outputs) for the RISC-V software baseline."""
from __future__ import annotations
import argparse, json
from pathlib import Path
import numpy as np, sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from snn_int import IntSNN, N_IN
ROOT = Path(__file__).resolve().parent.parent
ap = argparse.ArgumentParser()
ap.add_argument("model", type=Path); ap.add_argument("--n_bins", type=int, default=16)
ap.add_argument("--start", type=int, default=0)
ap.add_argument("--out", type=Path, default=ROOT / "firmware" / "bmi_weights.h")
a = ap.parse_args()
m = np.load(a.model / "model_int.npz"); meta = json.load(open(a.model / "train.json"))
d = np.load(ROOT / "data" / "prepared" / f"{meta['session']}.npz")
X = d["spikes"] > 0; lo = int(d["ind_test"][0]) + a.start; hi = lo + a.n_bins
ref = IntSNN(m["W1"].astype(np.int64), m["W2"].astype(np.int64), int(m["theta"]), int(m["k1"]), int(m["k2"]))
Y, S = ref.run(X[lo:hi])
toks = []
for t in range(lo, hi):
    toks += list(np.flatnonzero(X[t])); toks.append(0xFF)
H = m["W1"].shape[1]
def carr(name, typ, vals): return f"static const {typ} {name}[{len(vals)}] = {{" + ", ".join(str(int(x)) for x in vals) + "};\n"
s = "/* Auto-generated by sw/export_firmware.py */\n#ifndef BMI_WEIGHTS_H\n#define BMI_WEIGHTS_H\n#include <stdint.h>\n"
s += f"#define BMI_NIN {N_IN}\n#define BMI_H {H}\n#define BMI_THETA {int(m['theta'])}\n#define BMI_K1 {int(m['k1'])}\n#define BMI_K2 {int(m['k2'])}\n"
s += f"#define BMI_NBINS {a.n_bins}\n#define BMI_NTOK {len(toks)}\n"
s += carr("W1", "int8_t", m["W1"].reshape(-1)) + carr("W2", "int8_t", m["W2"].reshape(-1))
s += carr("STREAM", "uint8_t", toks) + carr("EXPECT", "int32_t", Y.reshape(-1)) + "#endif\n"
a.out.write_text(s)
print(f"wrote {a.out}: {a.n_bins} bins, {len(toks)-a.n_bins} events, {int(S.sum())} hidden spikes, "
      f"DMEM data ~{H*97 + 2*H + len(toks) + 8*a.n_bins} B")
