#!/usr/bin/env python3
"""Generate flat top-level modules for the core variants from rtl/bmi_snn_par.v / rtl/bmi_snn_top.v:
renamed module, parameter defaults replaced, compile-time options as `define lines, and (latch memory) the per-row clock
gates written out at module level - so that the hardened netlist has no hierarchy and no dotted instance names."""
import re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
PAR, TOP = "bmi_snn_par.v", "bmi_snn_top.v"
VARIANTS = {
    # name:            source, parameter defaults, compile-time options
    "bmi_snn_hw":    (PAR, dict(H=64, HARDWIRED=1, V_BITS=20, O_BITS=24, DENSE=1), []),
    "bmi_snn_scmem": (PAR, dict(H=64, HARDWIRED=0, V_BITS=20, O_BITS=24, DENSE=1), []),
    "bmi_snn_min":   (PAR, dict(H=64, HARDWIRED=1, V_BITS=16, O_BITS=16, DENSE=0), []),
    "bmi_snn_min32": (PAR, dict(H=32, HARDWIRED=1, V_BITS=16, O_BITS=16, DENSE=0), []),
    "bmi_snn_min16": (PAR, dict(H=16, HARDWIRED=1, V_BITS=16, O_BITS=16, DENSE=0), []),
    # phase 3: latch memory, datapath clock gating, narrower state, pruned weights, gated SRAM core
    "bmi_snn_lmem":  (PAR, dict(H=64, HARDWIRED=0, V_BITS=20, O_BITS=24, DENSE=1), ["LATCH_MEM"]),
    "bmi_snn_lmin":  (PAR, dict(H=64, HARDWIRED=0, V_BITS=12, O_BITS=14, DENSE=0), ["LATCH_MEM", "GATE_DP"]),
    "bmi_snn_ming":  (PAR, dict(H=64, HARDWIRED=1, V_BITS=16, O_BITS=16, DENSE=0), ["GATE_DP"]),
    "bmi_snn_m12":   (PAR, dict(H=64, HARDWIRED=1, V_BITS=12, O_BITS=14, DENSE=0), ["GATE_DP"]),
    "bmi_snn_sp":    (PAR, dict(H=64, HARDWIRED=1, V_BITS=12, O_BITS=14, DENSE=0), ["GATE_DP"]),   # weights pruned to 25 %:   rtl/sp/weights_rom.vh
    "bmi_snn_sp8":   (PAR, dict(H=64, HARDWIRED=1, V_BITS=12, O_BITS=14, DENSE=0), ["GATE_DP"]),   # weights pruned to 12.5 % (rtl/sp8): below the R2 gate, not hardened
    "bmi_snn_topg":  (TOP, dict(), ["GATE_MEM"]),
}
def latch_icgs(H):
    L = ["  // integrated clock gates of the latch memory (generated by sw/gen_variant.py): one per W1 row, one per W2 word"]
    L += [f"  sky130_fd_sc_hd__dlclkp_1 u_icg_r{c} (.CLK(wr_clk), .GATE(row_we_q1[{c}]), .GCLK(row_gclk[{c}]));" for c in range(97)]
    L += [f"  sky130_fd_sc_hd__dlclkp_1 u_icg_j{j} (.CLK(wr_clk), .GATE(w2_we_q1[{j}]), .GCLK(w2_gclk[{j}]));" for j in range(H)]
    return "\n".join(L)
out_dir = ROOT / "rtl/gen"; out_dir.mkdir(exist_ok=True)
only = sys.argv[1:]
for name, (src, prm, defs) in VARIANTS.items():
    if only and name not in only: continue
    s = (ROOT / "rtl" / src).read_text()
    s, n = re.subn(r"module bmi_snn_(par|top) #\(", f"module {name} #(", s); assert n == 1
    for k, v in prm.items():
        s, n = re.subn(rf"(parameter integer {k}\s*=\s*)\d+", rf"\g<1>{v}", s)
        assert n == 1, (name, k)
    defs = list(defs)
    if "LATCH_MEM" in defs:
        defs.append("LATCH_ICG_GENERATED")
        assert "//@@LATCH_ICG@@" in s
        s = s.replace("  //@@LATCH_ICG@@", latch_icgs(prm["H"]))
    head = f"// GENERATED by sw/gen_variant.py from rtl/{src} — do not edit; variant {name}: {prm} {defs}\n"
    head += "".join(f"`define {d}\n" for d in defs)
    (out_dir / f"{name}.v").write_text(head + s); print("wrote", out_dir / f"{name}.v", prm, defs)
