#!/usr/bin/env python3
"""Generate a flat top-level module for a parallel-core variant from rtl/bmi_snn_par.v
(renamed module, parameter defaults replaced) so that the hardened netlist has no hierarchy and no dotted names."""
import re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
VARIANTS = {
    "bmi_snn_hw":    dict(H=64, HARDWIRED=1, V_BITS=20, O_BITS=24, DENSE=1),
    "bmi_snn_scmem": dict(H=64, HARDWIRED=0, V_BITS=20, O_BITS=24, DENSE=1),
    "bmi_snn_min":   dict(H=64, HARDWIRED=1, V_BITS=16, O_BITS=16, DENSE=0),
    "bmi_snn_min32": dict(H=32, HARDWIRED=1, V_BITS=16, O_BITS=16, DENSE=0),
    "bmi_snn_min16": dict(H=16, HARDWIRED=1, V_BITS=16, O_BITS=16, DENSE=0),
}
src = (ROOT / "rtl/bmi_snn_par.v").read_text()
out_dir = ROOT / "rtl/gen"; out_dir.mkdir(exist_ok=True)
for name, prm in VARIANTS.items():
    s = src.replace("module bmi_snn_par #(", f"module {name} #(")
    for k, v in prm.items():
        s, n = re.subn(rf"(parameter integer {k}\s*=\s*)\d+", rf"\g<1>{v}", s)
        assert n == 1, (name, k)
    s = f"// GENERATED by sw/gen_variant.py from rtl/bmi_snn_par.v — do not edit; variant {name}: {prm}\n" + s
    (out_dir / f"{name}.v").write_text(s); print("wrote", out_dir / f"{name}.v", prm)
