#!/usr/bin/env python3
"""Generate rtl/weights_rom.vh (hardwired weights) from a trained model_int.npz."""
import sys, numpy as np
from pathlib import Path
m = np.load(Path(sys.argv[1]) / "model_int.npz"); out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / "rtl" / "weights_rom.vh"
W1 = m["W1"].astype(np.int64); W2 = m["W2"].astype(np.int64); H = W1.shape[1]
L = [f"// Auto-generated by sw/gen_weights_rom.py from {sys.argv[1]} — hardwired weights (H={H})",
     f"function [{8*H-1}:0] rom_row(input [6:0] r);", "  case (r)"]
for c in range(97):
    val = 0
    for j in range(H): val |= (int(W1[c, j]) & 0xFF) << (8 * j)
    L.append(f"    7'd{c}: rom_row = {8*H}'h{val:0{2*H}x};")
L += [f"    default: rom_row = {8*H}'d0;", "  endcase", "endfunction"]
v0 = 0; v1 = 0
for j in range(H):
    v0 |= (int(W2[j, 0]) & 0xFF) << (8 * j); v1 |= (int(W2[j, 1]) & 0xFF) << (8 * j)
L += [f"function [{8*H-1}:0] rom_w2_0(input dummy); rom_w2_0 = {8*H}'h{v0:0{2*H}x}; endfunction",
      f"function [{8*H-1}:0] rom_w2_1(input dummy); rom_w2_1 = {8*H}'h{v1:0{2*H}x}; endfunction"]
out.write_text("\n".join(L) + "\n"); print("wrote", out, "rows 97 x", 8*H, "bits")
