#!/usr/bin/env python3
"""Generate flat top-level modules for the core variants from rtl/bmi_snn_par.v / rtl/bmi_snn_top.v:
renamed module, parameter defaults replaced, compile-time options as `define lines, and (latch memory) the per-row clock
gates written out at module level - so that the hardened netlist has no hierarchy and no dotted instance names."""
import re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
PAR, TOP = "bmi_snn_par.v", "bmi_snn_top.v"
VARIANTS = {
    # name:            source, parameter defaults, compile-time options
    "bmi_snn_hw":    (PAR, dict(H=64, HARDWIRED=1, V_BITS=20, O_BITS=24, DENSE=1), []),
    "bmi_snn_scmem": (PAR, dict(H=64, HARDWIRED=0, V_BITS=20, O_BITS=24, DENSE=1), []),
    "bmi_snn_min":   (PAR, dict(H=64, HARDWIRED=1, V_BITS=16, O_BITS=16, DENSE=0), []),
    "bmi_snn_min32": (PAR, dict(H=32, HARDWIRED=1, V_BITS=16, O_BITS=16, DENSE=0), []),
    "bmi_snn_min16": (PAR, dict(H=16, HARDWIRED=1, V_BITS=16, O_BITS=16, DENSE=0), []),
    # phase 3: latch memory, datapath clock gating, narrower state, pruned weights, gated SRAM core
    "bmi_snn_lmem":  (PAR, dict(H=64, HARDWIRED=0, V_BITS=20, O_BITS=24, DENSE=1), ["LATCH_MEM"]),
    "bmi_snn_lmin":  (PAR, dict(H=64, HARDWIRED=0, V_BITS=12, O_BITS=14, DENSE=0), ["LATCH_MEM", "GATE_DP"]),
    "bmi_snn_ming":  (PAR, dict(H=64, HARDWIRED=1, V_BITS=16, O_BITS=16, DENSE=0), ["GATE_DP"]),
    "bmi_snn_m12":   (PAR, dict(H=64, HARDWIRED=1, V_BITS=12, O_BITS=14, DENSE=0), ["GATE_DP"]),
    "bmi_snn_sp":    (PAR, dict(H=64, HARDWIRED=1, V_BITS=12, O_BITS=14, DENSE=0), ["GATE_DP"]),   # weights pruned to 25 %:   rtl/sp/weights_rom.vh
    "bmi_snn_sp8":   (PAR, dict(H=64, HARDWIRED=1, V_BITS=12, O_BITS=14, DENSE=0), ["GATE_DP"]),   # weights pruned to 12.5 % (rtl/sp8): below the R2 gate, not hardened
    "bmi_snn_lmem2": (PAR, dict(H=64, HARDWIRED=0, V_BITS=20, O_BITS=24, DENSE=1), ["LATCH_MEM", "W2_PIPE"]),            # + pipelined W2 read
    "bmi_snn_lmin2": (PAR, dict(H=64, HARDWIRED=0, V_BITS=12, O_BITS=14, DENSE=0), ["LATCH_MEM", "GATE_DP", "W2_PIPE"]),
    "bmi_snn_topg":  (TOP, dict(), ["GATE_MEM"]),
}
def latch_icgs(H):
    L = ["  // integrated clock gates of the latch memory (generated by sw/gen_variant.py): one per W1 row, one per W2 word"]
    L += [f"  sky130_fd_sc_hd__dlclkp_1 u_icg_r{c} (.CLK(wr_clk), .GATE(row_we_q1[{c}]), .GCLK(row_gclk[{c}]));" for c in range(97)]
    L += [f"  sky130_fd_sc_hd__dlclkp_1 u_icg_j{j} (.CLK(wr_clk), .GATE(w2_we_q1[{j}]), .GCLK(w2_gclk[{j}]));" for j in range(H)]
    return "\n".join(L)
# ---- multi-PDK study: the integrated clock-gate cell of each library (the only technology-specific cell in the RTL)
#      instantiation template: {name} = instance name, {clk} {en} {gclk} = nets
ICG = {
    "sky130":    "sky130_fd_sc_hd__dlclkp_4 {name} (.CLK({clk}), .GATE({en}), .GCLK({gclk}));",
    "gf180":     "gf180mcu_fd_sc_mcu7t5v0__icgtp_4 {name} (.CLK({clk}), .E({en}), .TE(1'b0), .Q({gclk}));",
    "ihp":       "sg13g2_lgcp_1 {name} (.CLK({clk}), .GATE({en}), .GCLK({gclk}));",
    "asap7":     "ICGx1_ASAP7_75t_R {name} (.CLK({clk}), .ENA({en}), .SE(1'b0), .GCLK({gclk}));",
    "nangate45": "CLKGATE_X1 {name} (.CK({clk}), .E({en}), .GCK({gclk}));",
}
ICG_RE = re.compile(r"sky130_fd_sc_hd__dlclkp_\d (\w+) \(\.CLK\((\w+)\), \.GATE\(([^)]*\))\)?, \.GCLK\((\w+)\)\);")
def retarget(src: str, pdk: str, rom_dir: Path) -> str:
    """Replace the sky130 clock gates by the PDK's cell and inline the weight ROM (no include directories in other flows)."""
    def sub(m):
        en = m.group(3)[:-1] if m.group(3).endswith(")") and m.group(3).count("(") < m.group(3).count(")") else m.group(3)
        return ICG[pdk].format(name=m.group(1), clk=m.group(2), en=en, gclk=m.group(4))
    out, n = ICG_RE.subn(sub, src)
    assert n >= 1, "no clock gate found"
    rom = (rom_dir / "weights_rom.vh").read_text()
    out = out.replace('    `include "weights_rom.vh"', rom)
    return f"// retargeted to {pdk} by sw/gen_variant.py --pdk (clock-gate cell substituted, ROM inlined)\n" + out
out_dir = ROOT / "rtl/gen"; out_dir.mkdir(exist_ok=True)
args = sys.argv[1:]
if args[:1] == ["--pdk"]:      # usage: gen_variant.py --pdk <pdk> <variant> [rom_dir]
    pdk, var = args[1], args[2]; rom_dir = Path(args[3]) if len(args) > 3 else ROOT / "rtl" / ("h16" if var.endswith("16") else "h32" if var.endswith("32") else "")
    src = (out_dir / f"{var}.v").read_text()
    d = out_dir / "pdk" / pdk; d.mkdir(parents=True, exist_ok=True)
    (d / f"{var}.v").write_text(retarget(src, pdk, rom_dir)); print("wrote", d / f"{var}.v"); sys.exit(0)
only = args
for name, (src, prm, defs) in VARIANTS.items():
    if only and name not in only: continue
    s = (ROOT / "rtl" / src).read_text()
    s, n = re.subn(r"module bmi_snn_(par|top) #\(", f"module {name} #(", s); assert n == 1
    for k, v in prm.items():
        s, n = re.subn(rf"(parameter integer {k}\s*=\s*)\d+", rf"\g<1>{v}", s)
        assert n == 1, (name, k)
    defs = list(defs)
    if "LATCH_MEM" in defs:
        defs.append("LATCH_ICG_GENERATED")
        assert "//@@LATCH_ICG@@" in s
        s = s.replace("  //@@LATCH_ICG@@", latch_icgs(prm["H"]))
    head = f"// GENERATED by sw/gen_variant.py from rtl/{src} — do not edit; variant {name}: {prm} {defs}\n"
    head += "".join(f"`define {d}\n" for d in defs)
    (out_dir / f"{name}.v").write_text(head + s); print("wrote", out_dir / f"{name}.v", prm, defs)
