#!/usr/bin/env python3
"""Convert the per-signal toggle counts of tools/vcd_toggles (streamed from a gate-level VCD) into OpenSTA activity commands.

For every variable of the dumped scope that is a cell pin (<instance>/<port>) or a top-level port, one
    set_power_activity -pins|-input_ports {<name>} -activity <transitions per clock cycle> -duty <high-time fraction>
with the same definitions as OpenSTA's read_power_activities -vcd (transitions / duration, high time / duration; the initial value
does not count, x/z transitions count 0.5), and OpenSTA's Verilog-to-STA name conversion for escaped identifiers. Round 5 (E4/E7):
lets a full test block be accumulated without storing the waveform, then annotated in one OpenSTA run.
Usage: toggles_to_activity.py <toggles.tsv> --scope tb_bmi_snn/u_dut --period-s 200e-9 -o activity.tcl [--summary summary.json]"""
import argparse, json, sys
ap = argparse.ArgumentParser()
ap.add_argument("tsv"); ap.add_argument("--scope", required=True, help="VCD scope of the design (as in read_power_activities -scope)")
ap.add_argument("--period-s", type=float, required=True, help="clock period in seconds (activity is per clock cycle)")
ap.add_argument("-o", "--out", required=True); ap.add_argument("--summary", default=None)
a = ap.parse_args()

def v2sta(comp: str) -> str:
    """OpenSTA verilogToSta: drop the leading backslash of an escaped identifier and escape [ ] / and backslash inside it."""
    if comp.startswith("\\"):
        comp = comp[1:].rstrip()
        return "".join(("\\" + c) if c in "[]/\\" else c for c in comp)
    return comp

hdr = {}; rows = []
with open(a.tsv) as fh:
    for line in fh:
        if line.startswith("#"):
            k, v = line[1:].rstrip("\n").split("\t"); hdr[k] = float(v); continue
        f = line.rstrip("\n").split("\t"); bit = int(f[3]) if len(f) > 3 else None      # 4th column: bit index of a bus bit (name = the bus)
        rows.append((f[0], float(f[1]), float(f[2]), bit))
tscale = hdr["timescale_s"]; dur = (hdr["time_max"] - hdr["time_min"]) * tscale          # seconds
if dur <= 0: sys.exit("toggles_to_activity: zero duration")
pref = a.scope.rstrip("/") + "/"
n_pin = n_port = n_skip = 0; L = ["# generated by power/toggles_to_activity.py from " + a.tsv,
                                 f"# duration {dur:.6e} s, clock period {a.period_s:.6e} s, activity = transitions * period / duration",
                                 "set __n_pins 0; set __n_ports 0; set __n_nets 0",
                                 # a variable that is not a cell pin is a net (level-1 dumps such as the SoC waveform contain nets only):
                                 # its activity goes to the net's driver pin(s), as read_power_activities -vcd does; a top-level input
                                 # port is annotated as such
                                 "proc __net_act {net act duty} { set n [get_nets -quiet $net]; if {![llength $n]} { return 0 }; set drv {}",
                                 "  foreach p [get_pins -quiet -of_objects $n] { if {[get_property $p direction] eq \"output\"} { lappend drv $p } }",
                                 "  if {[llength $drv]} { set_power_activity -pins $drv -activity $act -duty $duty; return 1 }; return 0 }",
                                 "proc __top_act {nm act duty} { set p [get_ports -quiet $nm]",
                                 "  if {[llength $p] && [get_property $p direction] eq \"input\"} { set_power_activity -input_ports $p -activity $act -duty $duty; incr ::__n_ports; return 1 }",
                                 "  if {[__net_act $nm $act $duty]} { incr ::__n_nets; return 1 }; return 0 }",
                                 "proc __pin_act {nm act duty} { if {[llength [get_pins -quiet $nm]]} { set_power_activity -pins $nm -activity $act -duty $duty; incr ::__n_pins; return 1 }",
                                 "  if {[__net_act $nm $act $duty]} { incr ::__n_nets; return 1 }; return 0 }"]
for name, tc, high, bit in rows:
    if not name.startswith(pref): n_skip += 1; continue
    rel = name[len(pref):]
    comps = rel.split("/")
    if bit is not None: comps[-1] = v2sta(comps[-1]) + f"[{bit}]"; sta_ready = True      # bus bit: escape the bus name, then the index
    else: sta_ready = False
    act = tc * a.period_s / dur; duty = high * tscale / dur
    duty = min(max(duty, 0.0), 1.0)
    if len(comps) == 1:                                   # top-level port or net (resolved in Tcl)
        nm = comps[0] if sta_ready else v2sta(comps[0])
        L.append(f"__top_act {{{nm}}} {act:.6g} {duty:.6f}")
        n_port += 1
    elif len(comps) == 2:                                 # cell or macro pin (or a hierarchical net)
        nm = v2sta(comps[0]) + "/" + (comps[1] if sta_ready else v2sta(comps[1]))
        L.append(f"__pin_act {{{nm}}} {act:.6g} {duty:.6f}")
        n_pin += 1
    else: n_skip += 1
L.append('puts "toggles_to_activity: annotated $__n_pins pins, $__n_ports input ports and $__n_nets nets (driver pins)"')
open(a.out, "w").write("\n".join(L) + "\n")
summ = {"tsv": a.tsv, "duration_s": dur, "period_s": a.period_s, "cycles": dur / a.period_s, "vars_pins": n_pin, "vars_top": n_port, "skipped": n_skip,
        "time_min": hdr["time_min"], "time_max": hdr["time_max"], "timescale_s": tscale}
if a.summary: json.dump(summ, open(a.summary, "w"), indent=1)
print(f"toggles_to_activity: {n_pin} pin vars, {n_port} top-level vars, {n_skip} skipped; duration {dur*1e6:.3f} us = {dur/a.period_s:.1f} cycles")
