#!/usr/bin/env python3
"""Functional copy of the IHP SG13G2 standard-cell Verilog models for Icarus gate-level simulation.

The vendor models (OpenROAD-flow-scripts platforms/ihp-sg13g2/verilog/sg13g2_stdcell.v, same in the IHP-Open-PDK) compute their
outputs from delayed_<pin> nets that only the $setuphold timing checks create; Icarus does not implement timing checks, so those
nets float and every sequential cell is X. This script (1) drops the specify blocks, (2) replaces delayed_<pin> by <pin>, and
(3) replaces sg13g2_dfrbp_1 and sg13g2_lgcp_1 (the only sequential cells in the bmi_snn_min16 netlist) by behavioural models with a
defined power-up state: Icarus ignores `initial` in UDPs, and ABC implemented the synchronous reset of one membrane flop as a
tautology in its own output (Q | ~Q), which X-simulation cannot resolve. Every flop is reset by the RTL, so the power-up value
changes nothing after reset (the functional GLS is bit-exact against the reference vectors).
Usage: sim/gen_ihp_models.py [<platform sg13g2_stdcell.v>] [<output .v>]"""
import re, sys
src = sys.argv[1] if len(sys.argv) > 1 else "/media/pdk/OpenROAD-flow-scripts/flow/platforms/ihp-sg13g2/verilog/sg13g2_stdcell.v"
dst = sys.argv[2] if len(sys.argv) > 2 else "/media/pdk/ihp_sg13g2_models_functional.v"
s = open(src).read()
s = re.sub(r"\n\s*specify\b.*?\bendspecify\s*", "\n", s, flags=re.S)
s = s.replace("delayed_", "")
for mod in ("sg13g2_dfrbp_1", "sg13g2_lgcp_1"):
    s, n = re.subn(r"\nmodule\s+%s\s*\(.*?\nendmodule" % re.escape(mod), "", s, flags=re.S)
    assert n == 1, mod
hdr = ("// Functional copy of OpenROAD-flow-scripts platforms/ihp-sg13g2/verilog/sg13g2_stdcell.v (rev b4dbcb4) for Icarus: specify blocks removed and the\n"
       "// delayed_* nets (created only by $setuphold timing checks) replaced by the pins themselves. Generated by sim/gen_ihp_models.py.\n"
       "// sg13g2_dfrbp_1 and sg13g2_lgcp_1 are replaced by behavioural models with a defined power-up state (see the note at the end). README step 5e.\n")
beh = r'''
// ---- behavioural replacements (functional copy for Icarus): the UDP-based originals cannot be initialised (Icarus ignores UDP
// `initial`), and ABC implemented the synchronous reset of some membrane flops as a tautology in their own output (Q | ~Q),
// which X-simulation cannot resolve. Every flop is reset by the RTL, so the defined power-up value changes nothing after reset.
module sg13g2_dfrbp_1 (Q, Q_N, D, RESET_B, CLK);
	output Q, Q_N;
	input D, RESET_B, CLK;
	reg IQ = 1'b0;
	always @(posedge CLK or negedge RESET_B)
		if (!RESET_B) IQ <= 1'b0; else IQ <= D;
	assign Q = IQ;
	assign Q_N = ~IQ;
endmodule
module sg13g2_lgcp_1 (GCLK, GATE, CLK);
	output GCLK;
	input GATE, CLK;
	reg en_l = 1'b0;
	always @(CLK or GATE) if (!CLK) en_l = GATE;   // latch transparent in the low phase
	assign GCLK = CLK & en_l;
endmodule
'''
open(dst, "w").write(hdr + s + beh)
print(f"wrote {dst}: {s.count('module ')} cell models, dfrbp_1 and lgcp_1 behavioural")
