#!/usr/bin/env bash
# Round 5 (E1): utilization policy for the SRAM-macro cores (bmi_snn_top, bmi_snn_topg), whose floorplan is absolute.
# The die height stays 900 um (macro 674.48 x 781.92 um at [50, 50]); the die width is computed from the target standard-cell
# utilization U of the non-macro core area: core = A_macro + A_std / U, W = core / (H - 2 m) + 2 m with the 50 MHz core margin
# m = 10.3 um; A_std is the standard-cell area of the 50 MHz hardening (156,832 um2 for bmi_snn_top).
# Usage: synthesis/harden_policy_top.sh <design> [clock_ns=200] [utilizations="60 50 40 30 20"] ; env A_STD_UM2 overrides A_std.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; D="$1"; CLK="${2:-200}"; UTILS="${3:-60 50 40 30 20}"; B="$(basename "$D")"
DES="$ROOT/synthesis/$D"; SRC="$DES/config.yaml"; CFG="$DES/config_5mhz.yaml"
A_MACRO=527389; A_STD="${A_STD_UM2:-$(python3 -c "import json;print(json.load(open('$DES/runs/$B/final/metrics.json'))['design__instance__area__stdcell'])")}"
H=900; M=10.3
python3 - "$SRC" "$CFG" "$CLK" <<'PY'
import sys, re
src, dst, clk = sys.argv[1], sys.argv[2], sys.argv[3]
s = open(src).read()
s = re.sub(r"^CLOCK_PERIOD:.*$", f"CLOCK_PERIOD: {clk}", s, flags=re.M)
s = re.sub(r"^SYNTH_STRATEGY:.*\n", "", s, flags=re.M)
s = re.sub(r"^DRT_OPT_ITERS:.*\n", "", s, flags=re.M)
s = re.sub(r"^RUN_HEURISTIC_DIODE_INSERTION:.*$", "RUN_HEURISTIC_DIODE_INSERTION: false   # round 5: heuristic diodes broke legalization at 50-60 % utilization; diodes on input ports only", s, flags=re.M)
s = re.sub(r"^(RUN_HEURISTIC_DIODE_INSERTION:.*)$", r"\1\nDIODE_ON_PORTS: in", s, flags=re.M)
s = re.sub(r"^DIE_AREA:.*$", "DIE_AREA: [0, 0, @DIEW@, 900]   # round 5: width from the target standard-cell utilization (see harden_policy_top.sh)", s, flags=re.M)
s = re.sub(r"^CORE_AREA:.*$", "CORE_AREA: [20, 20, @COREX@, 880]", s, flags=re.M)
s = re.sub(r"^PL_TARGET_DENSITY_PCT:.*$", "PL_TARGET_DENSITY_PCT: @DENS@", s, flags=re.M)
s = "# Round-5 configuration (E1): common 5 MHz clock, utilization policy (absolute die from the target utilization); generated by synthesis/harden_policy_top.sh\n" + s
open(dst + ".tmpl", "w").write(s)
PY
for U in $UTILS; do
  DENS=$((U + 10)); [ $DENS -gt 95 ] && DENS=95
  W=$(python3 -c "import math; core=$A_MACRO + $A_STD/($U/100); w=core/($H-2*$M)+2*$M; print(int(math.ceil(w/10.0)*10))")
  sed -e "s/@DIEW@/$W/" -e "s/@COREX@/$((W - 20))/" -e "s/@DENS@/$DENS/" "$CFG.tmpl" > "$CFG"
  TAG="${B}_5m_u$U"; T0=$(date +%s)
  echo "==== $D: clock $CLK ns, target std-cell utilization $U % (die ${W} x $H um, density $DENS %), run tag $TAG ($(date +%H:%M))"
  DESIGN=$D CFG="$CFG" RUN_TAG=$TAG "$ROOT/synthesis/run_synthesis.sh" > "$ROOT/logs/openlane_$TAG.log" 2>&1
  SR="$DES/runs/$TAG/synthesis_results.txt"; MJ="$DES/runs/$TAG/final/metrics.json"
  DRC=$(python3 -c "import json,sys; m=json.load(open('$MJ')); print(m.get('route__drc_errors','NA'))" 2>/dev/null || echo NA)
  PASS=$(grep -c "RESULT: PASS" "$SR" 2>/dev/null || echo 0)
  DT=$(( ($(date +%s) - T0) / 60 ))
  grep -E "setup slack|hold slack|RESULT" "$SR" 2>/dev/null | sed 's/^/   /'
  echo "   drc_errors=$DRC timing_pass=$PASS runtime=${DT}min"
  if [ "$DRC" = "0" ] && [ "$PASS" = "1" ]; then
    ln -sfn "$TAG" "$DES/runs/${B}_5m"; cp "$CFG" "$DES/config_5mhz_used.yaml"
    echo "   -> accepted: runs/${B}_5m -> $TAG"; echo "$D ACCEPTED util=$U tag=$TAG runtime=${DT}min drc=$DRC die=${W}x$H" >> "$ROOT/logs/policy_round5.log"; exit 0
  fi
  echo "$D REJECTED util=$U tag=$TAG runtime=${DT}min drc=$DRC pass=$PASS die=${W}x$H" >> "$ROOT/logs/policy_round5.log"
  [ "$DRC" = "NA" ] && { echo "   run failed before routing metrics (see logs/openlane_$TAG.log)"; tail -n 5 "$ROOT/logs/openlane_$TAG.log"; }
done
echo "$D: no utilization in the policy list converged" | tee -a "$ROOT/logs/policy_round5.log"; exit 1
