#!/usr/bin/env bash
# Round 5 (E14): re-harden a sky130 core at 5 MHz with sky130_fd_sc_hd__ss_n40C_1v28 as the signoff (default) liberty, at the
# utilization accepted by the 5 MHz policy (synthesis/<design>/config_5mhz_used.yaml). The 1.28 V corner is added to the STA corners
# (nom/min/max) and becomes DEFAULT_CORNER, so synthesis, repair and signoff see it; the standard tt/ss/ff corners stay in the list.
# Usage: synthesis/harden_lowv.sh <design>     (waits for the 5 MHz acceptance; run tag <design>_5m_lv)
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; D="$1"; DES="$ROOT/synthesis/$D"; SRC="$DES/config_5mhz_used.yaml"; CFG="$DES/config_lowv.yaml"
while [[ ! -f "$SRC" ]]; do sleep 300; done
LIBD="/media/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib"
python3 - "$SRC" "$CFG" "$LIBD" <<'PY'
import sys, re
src, dst, libd = sys.argv[1:4]
s = open(src).read()
import os
lvu = os.environ.get("LV_UTIL")          # utilization override when the TT utilization does not route with the 1.28 V repair (policy step down)
if lvu:
    s = re.sub(r"^FP_CORE_UTIL:.*$", f"FP_CORE_UTIL: {lvu}", s, flags=re.M)
    s = re.sub(r"^PL_TARGET_DENSITY_PCT:.*$", f"PL_TARGET_DENSITY_PCT: {min(int(lvu) + 10, 95)}", s, flags=re.M)
extra = os.environ.get("LV_EXTRA_YAML", "")     # extra configuration lines for a retry (e.g. SYNTH_STRATEGY), replacing existing keys
if extra:
    for line in extra.split("\\n"):
        key = line.split(":")[0].strip()
        if key: s = re.sub(r"^" + re.escape(key) + r":.*\n", "", s, flags=re.M)
    s = s.rstrip("\n") + "\n# E14 retry amendment (LV_EXTRA_YAML)\n" + extra.replace("\\n", "\n") + "\n"
s = "# Round-5 configuration (E14): as config_5mhz_used.yaml, signoff liberty sky130_fd_sc_hd__ss_n40C_1v28 (generated by synthesis/harden_lowv.sh)\n" + s
s += f'''
# E14: low-voltage signoff corner (ss, -40 C, 1.28 V) as the default corner; the PDK corners are kept
LIB:
  "*_tt_025C_1v80": ["{libd}/sky130_fd_sc_hd__tt_025C_1v80.lib"]
  "*_ss_100C_1v60": ["{libd}/sky130_fd_sc_hd__ss_100C_1v60.lib"]
  "*_ff_n40C_1v95": ["{libd}/sky130_fd_sc_hd__ff_n40C_1v95.lib"]
  "*_ss_n40C_1v28": ["{libd}/sky130_fd_sc_hd__ss_n40C_1v28.lib"]
STA_CORNERS: [nom_ss_n40C_1v28, min_ss_n40C_1v28, max_ss_n40C_1v28, nom_tt_025C_1v80, nom_ss_100C_1v60, nom_ff_n40C_1v95, min_tt_025C_1v80, min_ss_100C_1v60, min_ff_n40C_1v95, max_tt_025C_1v80, max_ss_100C_1v60, max_ff_n40C_1v95]
DEFAULT_CORNER: nom_ss_n40C_1v28
TIMING_VIOLATION_CORNERS: ["*"]
# OpenROAD's timing-driven global placement crashes (silent exit in the resizer reweighting step) with the 1.28 V liberty as the
# default corner (bmi_snn_sp, 2026-09-19); wire-length-driven placement instead
PL_TIME_DRIVEN: false
'''
open(dst, "w").write(s)
PY
TAG="${D}_5m_lv${LV_TAG_SUFFIX:-}"; T0=$(date +%s); U=$(grep -E "^FP_CORE_UTIL:" "$CFG" | awk '{print $2}')
echo "==== $D: 5 MHz, utilization $U %, signoff ss_n40C_1v28, run tag $TAG ($(date +%H:%M))"
DESIGN=$D CFG="$CFG" RUN_TAG=$TAG "$ROOT/synthesis/run_synthesis.sh" > "$ROOT/logs/openlane_$TAG.log" 2>&1
SR="$DES/runs/$TAG/synthesis_results.txt"; MJ="$DES/runs/$TAG/final/metrics.json"
DRC=$(python3 -c "import json; m=json.load(open('$MJ')); print(m.get('route__drc_errors','NA'))" 2>/dev/null || echo NA)
PASS=$(grep -c "RESULT: PASS" "$SR" 2>/dev/null || true); PASS=${PASS:-0}; DT=$(( ($(date +%s) - T0) / 60 ))
grep -E "setup slack|hold slack|RESULT" "$SR" 2>/dev/null | sed 's/^/   /'
echo "   drc_errors=$DRC timing_pass=$PASS runtime=${DT}min"
echo "$D LOWV util=$U tag=$TAG runtime=${DT}min drc=$DRC pass=$PASS" >> "$ROOT/logs/policy_round5.log"
[ "$DRC" = "NA" ] && tail -n 8 "$ROOT/logs/openlane_$TAG.log"
