#!/usr/bin/env bash
# Round 5 (E5): harden a retargeted core on an OpenROAD-flow-scripts platform at the common 5 MHz clock with the utilization
# policy (60 % down in steps of 10 % until detailed routing converges and timing is met).
# Usage: synthesis/run_orfs5.sh <platform> <core> [flavour] [utils="60 50 40 30 20"]
#   platform: nangate45 | ihp-sg13g2 | asap7        flavour (asap7 only): rvt (default) | sram   (ASAP7_USESRAM=1: low-leakage library)
# Design dir: $ORFS/flow/designs/<platform>/<core>_5m[_sram]/ ; results under results/<platform>/<core>_5m[_sram]_u<util>/base ;
# the accepted run is recorded in logs/orfs5_policy.log and symlinked as results/<platform>/<core>_5m[_sram]/.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; PLAT="$1"; CORE="$2"; FLAV="${3:-rvt}"; UTILS="${4:-60 50 40 30 20}"
ORFS="${ORFS:-/media/pdk/OpenROAD-flow-scripts}"; OL2="${OPENLANE_ROOT:-/media/hardware_design_tools/openlane2}"
export PATH="/nix/var/nix/profiles/default/bin:$PATH"; source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh 2>/dev/null || true
case $PLAT in nangate45) P=nangate45; PER=200; TU=1;; ihp-sg13g2) P=ihp; PER=200; TU=1;; asap7) P=$([ "$FLAV" = sram ] && echo asapsram || echo asap7); PER=200000; TU=1e-3;; *) echo "platform?"; exit 2;; esac
RTLP=$([ "$P" = asapsram ] && echo asap7sram || echo $P)
NICK="${CORE}_5m"; [ "$FLAV" = sram ] && NICK="${CORE}_5m_sram"
DD="$ORFS/flow/designs/$PLAT/$NICK"; mkdir -p "$DD"
cat > "$DD/constraint.sdc" <<SDC
current_design $CORE
set clk_name clk
set clk_port_name clk
set clk_period $PER
set clk_io_pct 0.2
set clk_port [get_ports \$clk_port_name]
create_clock -name \$clk_name -period \$clk_period \$clk_port
set non_clock_inputs [lsearch -inline -all -not -exact [all_inputs] \$clk_port]
set_input_delay  [expr \$clk_period * \$clk_io_pct] -clock \$clk_name \$non_clock_inputs
set_output_delay [expr \$clk_period * \$clk_io_pct] -clock \$clk_name [all_outputs]
set_false_path -from [get_ports reset]
set_false_path -from [get_ports mode_dense]
SDC
if [ "$CORE" = bmi_snn_lmin2 ]; then cat >> "$DD/constraint.sdc" <<'SDC'
# latch-based weight memory: contents are static while decoding (writes only when idle) -> paths launched from the latches are
# false paths; the hold check at the latch data pins (data stable from the opening edge for a full cycle) is waived, as on sky130
set wlatches [all_registers -level_sensitive -cells]
if { [llength $wlatches] > 0 } { set_false_path -from $wlatches; set_false_path -hold -to [all_registers -level_sensitive -data_pins] }
SDC
fi
# (no set_propagated_clock in the SDC: the flow propagates the clocks after CTS; at floorplan the ideal clock avoids a premature hold repair through the nested clock gates)
LOGP="$ROOT/logs/orfs5_policy.log"
for U in $UTILS; do
  RUNNICK="${NICK}_u$U"; T0=$(date +%s)
  { echo "# Round 5 (E5): $CORE on $PLAT ($FLAV), 5 MHz, utilization $U % - generated by synthesis/run_orfs5.sh"
    echo "export DESIGN_NAME = $CORE"; echo "export DESIGN_NICKNAME = $RUNNICK"; echo "export PLATFORM = $PLAT"
    echo "export VERILOG_FILES = $ROOT/rtl/gen/pdk/$RTLP/$CORE.v"; echo "export SDC_FILE = ./designs/$PLAT/$NICK/constraint.sdc"
    echo "export CORE_UTILIZATION = $U"; [ "$PLAT" != ihp-sg13g2 ] && echo "export PLACE_DENSITY_LB_ADDON = 0.10"; echo "export TNS_END_PERCENT = 100"
    echo "export SYNTH_MEMORY_MAX_BITS = 65536"; echo "export ADDER_MAP_FILE :="; echo "export ABC_AREA = 1"
    echo "export REMOVE_ABC_BUFFERS = 1   # skip the floorplan-stage timing repair (wire-load hold repair through the nested clock gates hit the buffer limit); repair happens after placement/CTS"
    echo "export DETAILED_ROUTE_ARGS = -droute_end_iter 40 -verbose 1 -bottom_routing_layer \$(MIN_ROUTING_LAYER) -top_routing_layer \$(MAX_ROUTING_LAYER)"
    [ "$PLAT" = ihp-sg13g2 ] && { echo "export CELL_PAD_IN_SITES_GLOBAL_PLACEMENT = 1   # pin-access room for the IHP router (4/2 at 25 % in round 2; 1/0 keeps the padded utilization below the placement density here)"; echo "export CELL_PAD_IN_SITES_DETAIL_PLACEMENT = 0"; echo "export PLACE_DENSITY_LB_ADDON = 0.20"; }
    [ "$FLAV" = sram ] && echo "export ASAP7_USESRAM = 1"
  } > "$DD/config.mk"
  echo "==== $PLAT $FLAV $CORE: utilization $U % (nick $RUNNICK, $(date +%H:%M))"
  nix --extra-experimental-features "nix-command flakes" develop --accept-flake-config "$OL2" -c bash -c \
    "cd '$ORFS/flow' && make DESIGN_CONFIG=./designs/$PLAT/$NICK/config.mk OPENROAD_EXE=\$(which openroad) YOSYS_EXE=\$(which yosys) KLAYOUT_CMD=\$(which klayout)" > "$ROOT/logs/orfs5_${PLAT}_${RUNNICK}.log" 2>&1
  RC=$?; L="$ORFS/flow/logs/$PLAT/$RUNNICK/base"; DT=$(( ($(date +%s) - T0) / 60 ))
  read DRC SWS HWS <<< $(python3 - "$L" "$TU" <<'PY'
import json, sys, os
L, tu = sys.argv[1], float(sys.argv[2])
try: drc = json.load(open(os.path.join(L, "5_2_route.json"))).get("detailedroute__route__drc_errors", "NA")
except Exception: drc = "NA"
try:
    m = json.load(open(os.path.join(L, "6_report.json"))); s = m.get("finish__timing__setup__ws"); h = m.get("finish__timing__hold__ws")
    sws = "NA" if s is None else f"{s*tu:.3f}"; hws = "NA" if h is None else f"{h*tu:.3f}"
except Exception: sws = hws = "NA"
print(drc, sws, hws)
PY
)
  echo "   rc=$RC drc=$DRC setup_ws_ns=$SWS hold_ws_ns=$HWS runtime=${DT}min"
  OK=$(python3 -c "print(1 if '$DRC'=='0' and '$SWS' not in ('NA','') and float('$SWS')>=0 and ('$HWS'=='NA' or float('$HWS')>=0) else 0)")
  if [ "$OK" = "1" ]; then
    ln -sfn "$RUNNICK" "$ORFS/flow/results/$PLAT/$NICK"; ln -sfn "$RUNNICK" "$ORFS/flow/logs/$PLAT/$NICK" 2>/dev/null; cp "$DD/config.mk" "$DD/config_used.mk"
    echo "$PLAT $FLAV $CORE ACCEPTED util=$U nick=$RUNNICK runtime=${DT}min setup=$SWS hold=$HWS" >> "$LOGP"; echo "   -> accepted"; exit 0
  fi
  echo "$PLAT $FLAV $CORE REJECTED util=$U nick=$RUNNICK runtime=${DT}min rc=$RC drc=$DRC setup=$SWS hold=$HWS" >> "$LOGP"
done
echo "$PLAT $FLAV $CORE: no utilization converged" | tee -a "$LOGP"; exit 1
