# Hardwired 16-bit H=16 SNN decoder core (github.com/AmirrezaYousefzadeh/sky130-snn-bmi), multi-PDK study
export DESIGN_NAME = bmi_snn_min16
export DESIGN_NICKNAME = bmi_snn_min16_abc
export PLATFORM    = ihp-sg13g2
export VERILOG_FILES = /home/yousefzadeha/workspace/BCI_paper/rtl/gen/pdk/ihp/bmi_snn_min16.v
export SDC_FILE      = ./designs/ihp-sg13g2/bmi_snn_min16/constraint.sdc
export CORE_UTILIZATION = 25   # 40 % did not route within 2 h (62k violations stuck)
export PLACE_DENSITY_LB_ADDON = 0.05
export CELL_PAD_IN_SITES_GLOBAL_PLACEMENT = 4   # room for pin access (via-sized Metal2 shorts at the Via1 landings otherwise)
export CELL_PAD_IN_SITES_DETAIL_PLACEMENT = 2
export TNS_END_PERCENT = 100
export SYNTH_MEMORY_MAX_BITS = 65536   # the hardwired weight ROM is a 97 x 128-bit case statement
export ADDER_MAP_FILE :=   # the platform full-adder techmap (FA/HA cells) alters the arithmetic of this design (bit-exact GLS fails); plain gates instead
export ABC_AREA = 1   # area-oriented ABC script: halves the high-fanout nets of the 97-way weight decode; with it the detail router closes (0 violations, 16 iterations)
export DETAILED_ROUTE_ARGS = -droute_end_iter 25 -verbose 1 -bottom_routing_layer Metal2 -top_routing_layer Metal5   # safety bound; the route closes at iteration 16
